//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace MeisterGeister.Model
{
    [DataContract(IsReference=true)]
    public partial class Alchimierezept : INotifyPropertyChanged
    {
        #region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    	
    	/// <summary>
        /// Notifies listeners that a property value has changed.
        /// </summary>
        /// <param name="propertyName">Name of the property used to notify listeners.  This
        /// value is optional and can be provided automatically when invoked from compilers
        /// that support <see cref="CallerMemberNameAttribute"/>.</param>
        protected void OnChanged([CallerMemberName] string propertyName = null)
        {
            var eventHandler = this.PropertyChanged;
            if (eventHandler != null)
            {
                eventHandler(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        #endregion

        #region ValidatePropertyChanging
    	protected event Extensions.ValidatePropertyChangingEventHandler ValidatePropertyChanging;
    
    	protected void OnValidatePropertyChanging(object currentValue, object newValue, [CallerMemberName] string propertyName = null)
    	{
    		if(ValidatePropertyChanging != null)
    		{
    			ValidatePropertyChanging(this, propertyName, currentValue, newValue);
    		}
    	}

        #endregion

        #region Set
    	/// <summary>
        /// Checks if a property already matches a desired value.  Sets the property and
        /// notifies listeners only when necessary.
        /// </summary>
        /// <typeparam name="T">Type of the property.</typeparam>
        /// <param name="storage">Reference to a property with both getter and setter.</param>
        /// <param name="value">Desired value for the property.</param>
        /// <param name="propertyName">Name of the property used to notify listeners.  This
        /// value is optional and can be provided automatically when invoked from compilers that
        /// support CallerMemberName.</param>
        /// <returns>True if the value was changed, false if the existing value matched the
        /// desired value.</returns>
        protected bool Set<T>(ref T storage, T value, [CallerMemberName] String propertyName = null)
        {
            if (object.Equals(storage, value)) return false;
    
    		OnValidatePropertyChanging(storage, value, propertyName);
    		storage = value;
    		OnChanged(propertyName);
            return true;
        }

        #endregion

        #region Primitive Properties
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid AlchimierezeptGUID
        {
            get { return _alchimierezeptGUID; }
            set
    		{ 
    			Set(ref _alchimierezeptGUID, value);
    		}
    
        }
        private System.Guid _alchimierezeptGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Name
        {
            get { return _name; }
            set
    		{ 
    			Set(ref _name, value);
    		}
    
        }
        private string _name;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Gruppe
        {
            get { return _gruppe; }
            set
    		{ 
    			Set(ref _gruppe, value);
    		}
    
        }
        private string _gruppe;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Kategorie
        {
            get { return _kategorie; }
            set
    		{ 
    			Set(ref _kategorie, value);
    		}
    
        }
        private string _kategorie;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Merkmale
        {
            get { return _merkmale; }
            set
    		{ 
    			Set(ref _merkmale, value);
    		}
    
        }
        private string _merkmale;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int Brauschwierigkeit
        {
            get { return _brauschwierigkeit; }
            set
    		{ 
    			Set(ref _brauschwierigkeit, value);
    		}
    
        }
        private int _brauschwierigkeit;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int Analyseschwierigkeit
        {
            get { return _analyseschwierigkeit; }
            set
    		{ 
    			Set(ref _analyseschwierigkeit, value);
    		}
    
        }
        private int _analyseschwierigkeit;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int Beschaffungsschwierigkeit
        {
            get { return _beschaffungsschwierigkeit; }
            set
    		{ 
    			Set(ref _beschaffungsschwierigkeit, value);
    		}
    
        }
        private int _beschaffungsschwierigkeit;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual double Beschaffungskosten
        {
            get { return _beschaffungskosten; }
            set
    		{ 
    			Set(ref _beschaffungskosten, value);
    		}
    
        }
        private double _beschaffungskosten;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Haltbarkeit
        {
            get { return _haltbarkeit; }
            set
    		{ 
    			Set(ref _haltbarkeit, value);
    		}
    
        }
        private string _haltbarkeit;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Haltbarkeitseinheit
        {
            get { return _haltbarkeitseinheit; }
            set
    		{ 
    			Set(ref _haltbarkeitseinheit, value);
    		}
    
        }
        private string _haltbarkeitseinheit;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Labor
        {
            get { return _labor; }
            set
    		{ 
    			Set(ref _labor, value);
    		}
    
        }
        private string _labor;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Zutaten
        {
            get { return _zutaten; }
            set
    		{ 
    			Set(ref _zutaten, value);
    		}
    
        }
        private string _zutaten;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Substitute
        {
            get { return _substitute; }
            set
    		{ 
    			Set(ref _substitute, value);
    		}
    
        }
        private string _substitute;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Bemerkung
        {
            get { return _bemerkung; }
            set
    		{ 
    			Set(ref _bemerkung, value);
    		}
    
        }
        private string _bemerkung;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Literatur
        {
            get { return _literatur; }
            set
    		{ 
    			Set(ref _literatur, value);
    		}
    
        }
        private string _literatur;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Tags
        {
            get { return _tags; }
            set
    		{ 
    			Set(ref _tags, value);
    		}
    
        }
        private string _tags;

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual ICollection<Alchimierezept_Setting> Alchimierezept_Setting
        {
            get
            {
                if (_alchimierezept_Setting == null)
                {
                    var newCollection = new FixupCollection<Alchimierezept_Setting>();
                    newCollection.CollectionChanged += FixupAlchimierezept_Setting;
                    _alchimierezept_Setting = newCollection;
                }
                return _alchimierezept_Setting;
            }
            set
            {
                if (!ReferenceEquals(_alchimierezept_Setting, value))
                {
                    var previousValue = _alchimierezept_Setting as FixupCollection<Alchimierezept_Setting>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupAlchimierezept_Setting;
                    }
                    _alchimierezept_Setting = value;
                    var newValue = value as FixupCollection<Alchimierezept_Setting>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupAlchimierezept_Setting;
                    }
                }
            }
        }
        private ICollection<Alchimierezept_Setting> _alchimierezept_Setting;

        #endregion

        #region Association Fixup
    
        private void FixupAlchimierezept_Setting(object sender, NotifyCollectionChangedEventArgs e)
        {
    		OnChanged("Alchimierezept_Setting");
            if (e.NewItems != null)
            {
                foreach (Alchimierezept_Setting item in e.NewItems)
                {
                    item.Alchimierezept = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Alchimierezept_Setting item in e.OldItems)
                {
                    if (ReferenceEquals(item.Alchimierezept, this))
                    {
                        item.Alchimierezept = null;
                    }
                }
            }
        }

        #endregion

    }
}
