//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace MeisterGeister.Model
{
    [DataContract(IsReference=true)]
    public partial class GegnerBase_Kampfregel : INotifyPropertyChanged
    {
        #region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    	
    	/// <summary>
        /// Notifies listeners that a property value has changed.
        /// </summary>
        /// <param name="propertyName">Name of the property used to notify listeners.  This
        /// value is optional and can be provided automatically when invoked from compilers
        /// that support <see cref="CallerMemberNameAttribute"/>.</param>
        protected void OnChanged([CallerMemberName] string propertyName = null)
        {
            var eventHandler = this.PropertyChanged;
            if (eventHandler != null)
            {
                eventHandler(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        #endregion

        #region ValidatePropertyChanging
    	protected event Extensions.ValidatePropertyChangingEventHandler ValidatePropertyChanging;
    
    	protected void OnValidatePropertyChanging(object currentValue, object newValue, [CallerMemberName] string propertyName = null)
    	{
    		if(ValidatePropertyChanging != null)
    		{
    			ValidatePropertyChanging(this, propertyName, currentValue, newValue);
    		}
    	}

        #endregion

        #region Set
    	/// <summary>
        /// Checks if a property already matches a desired value.  Sets the property and
        /// notifies listeners only when necessary.
        /// </summary>
        /// <typeparam name="T">Type of the property.</typeparam>
        /// <param name="storage">Reference to a property with both getter and setter.</param>
        /// <param name="value">Desired value for the property.</param>
        /// <param name="propertyName">Name of the property used to notify listeners.  This
        /// value is optional and can be provided automatically when invoked from compilers that
        /// support CallerMemberName.</param>
        /// <returns>True if the value was changed, false if the existing value matched the
        /// desired value.</returns>
        protected bool Set<T>(ref T storage, T value, [CallerMemberName] String propertyName = null)
        {
            if (object.Equals(storage, value)) return false;
    
    		OnValidatePropertyChanging(storage, value, propertyName);
    		storage = value;
    		OnChanged(propertyName);
            return true;
        }

        #endregion

        #region Primitive Properties
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid GegnerBaseGUID
        {
            get { return _gegnerBaseGUID; }
            set
            {
                if (_gegnerBaseGUID != value)
                {
                    if (GegnerBase != null && GegnerBase.GegnerBaseGUID != value)
                    {
                        GegnerBase = null;
                    }
                    _gegnerBaseGUID = value;
                }
            }
    
        }
        private System.Guid _gegnerBaseGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid KampfregelGUID
        {
            get { return _kampfregelGUID; }
            set
            {
                if (_kampfregelGUID != value)
                {
                    if (Kampfregel != null && Kampfregel.KampfregelGUID != value)
                    {
                        Kampfregel = null;
                    }
                    _kampfregelGUID = value;
                }
            }
    
        }
        private System.Guid _kampfregelGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int Erschwernis
        {
            get { return _erschwernis; }
            set
    		{ 
    			Set(ref _erschwernis, value);
    		}
    
        }
        private int _erschwernis;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string TP
        {
            get { return _tP; }
            set
    		{ 
    			Set(ref _tP, value);
    		}
    
        }
        private string _tP;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Bemerkung
        {
            get { return _bemerkung; }
            set
    		{ 
    			Set(ref _bemerkung, value);
    		}
    
        }
        private string _bemerkung;

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual GegnerBase GegnerBase
        {
            get { return _gegnerBase; }
            set
            {
                if (!ReferenceEquals(_gegnerBase, value))
                {
                    var previousValue = _gegnerBase;
                    _gegnerBase = value;
                    FixupGegnerBase(previousValue);
                }
            }
        }
        private GegnerBase _gegnerBase;
    
    	[DataMember]
        public virtual Kampfregel Kampfregel
        {
            get { return _kampfregel; }
            set
            {
                if (!ReferenceEquals(_kampfregel, value))
                {
                    var previousValue = _kampfregel;
                    _kampfregel = value;
                    FixupKampfregel(previousValue);
                }
            }
        }
        private Kampfregel _kampfregel;

        #endregion

        #region Association Fixup
    
        private void FixupGegnerBase(GegnerBase previousValue)
        {
    		OnChanged("GegnerBase");
            if (previousValue != null && previousValue.GegnerBase_Kampfregel.Contains(this))
            {
                previousValue.GegnerBase_Kampfregel.Remove(this);
            }
    
            if (GegnerBase != null)
            {
                if (!GegnerBase.GegnerBase_Kampfregel.Contains(this))
                {
                    GegnerBase.GegnerBase_Kampfregel.Add(this);
                }
                if (GegnerBaseGUID != GegnerBase.GegnerBaseGUID)
                {
                    GegnerBaseGUID = GegnerBase.GegnerBaseGUID;
                }
            }
        }
    
        private void FixupKampfregel(Kampfregel previousValue)
        {
    		OnChanged("Kampfregel");
            if (previousValue != null && previousValue.GegnerBase_Kampfregel.Contains(this))
            {
                previousValue.GegnerBase_Kampfregel.Remove(this);
            }
    
            if (Kampfregel != null)
            {
                if (!Kampfregel.GegnerBase_Kampfregel.Contains(this))
                {
                    Kampfregel.GegnerBase_Kampfregel.Add(this);
                }
                if (KampfregelGUID != Kampfregel.KampfregelGUID)
                {
                    KampfregelGUID = Kampfregel.KampfregelGUID;
                }
            }
        }

        #endregion

    }
}
