//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace MeisterGeister.Model
{
    [DataContract(IsReference=true)]
    public partial class Held_VorNachteil : INotifyPropertyChanged
    {
        #region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    	
    	/// <summary>
        /// Notifies listeners that a property value has changed.
        /// </summary>
        /// <param name="propertyName">Name of the property used to notify listeners.  This
        /// value is optional and can be provided automatically when invoked from compilers
        /// that support <see cref="CallerMemberNameAttribute"/>.</param>
        protected void OnChanged([CallerMemberName] string propertyName = null)
        {
            var eventHandler = this.PropertyChanged;
            if (eventHandler != null)
            {
                eventHandler(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        #endregion

        #region ValidatePropertyChanging
    	protected event Extensions.ValidatePropertyChangingEventHandler ValidatePropertyChanging;
    
    	protected void OnValidatePropertyChanging(object currentValue, object newValue, [CallerMemberName] string propertyName = null)
    	{
    		if(ValidatePropertyChanging != null)
    		{
    			ValidatePropertyChanging(this, propertyName, currentValue, newValue);
    		}
    	}

        #endregion

        #region Set
    	/// <summary>
        /// Checks if a property already matches a desired value.  Sets the property and
        /// notifies listeners only when necessary.
        /// </summary>
        /// <typeparam name="T">Type of the property.</typeparam>
        /// <param name="storage">Reference to a property with both getter and setter.</param>
        /// <param name="value">Desired value for the property.</param>
        /// <param name="propertyName">Name of the property used to notify listeners.  This
        /// value is optional and can be provided automatically when invoked from compilers that
        /// support CallerMemberName.</param>
        /// <returns>True if the value was changed, false if the existing value matched the
        /// desired value.</returns>
        protected bool Set<T>(ref T storage, T value, [CallerMemberName] String propertyName = null)
        {
            if (object.Equals(storage, value)) return false;
    
    		OnValidatePropertyChanging(storage, value, propertyName);
    		storage = value;
    		OnChanged(propertyName);
            return true;
        }

        #endregion

        #region Primitive Properties
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid HeldGUID
        {
            get { return _heldGUID; }
            set
            {
                if (_heldGUID != value)
                {
                    if (Held != null && Held.HeldGUID != value)
                    {
                        Held = null;
                    }
                    _heldGUID = value;
                }
            }
    
        }
        private System.Guid _heldGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid VorNachteilGUID
        {
            get { return _vorNachteilGUID; }
            set
            {
                if (_vorNachteilGUID != value)
                {
                    if (VorNachteil != null && VorNachteil.VorNachteilGUID != value)
                    {
                        VorNachteil = null;
                    }
                    _vorNachteilGUID = value;
                }
            }
    
        }
        private System.Guid _vorNachteilGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Wert
        {
            get { return _wert; }
            set
    		{ 
    			Set(ref _wert, value);
    		}
    
        }
        private string _wert;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual long Id
        {
            get { return _id; }
            set
    		{ 
    			Set(ref _id, value);
    		}
    
        }
        private long _id;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual double KostenGrund
        {
            get { return _kostenGrund; }
            set
    		{ 
    			Set(ref _kostenGrund, value);
    		}
    
        }
        private double _kostenGrund;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual double KostenFaktor
        {
            get { return _kostenFaktor; }
            set
    		{ 
    			Set(ref _kostenFaktor, value);
    		}
    
        }
        private double _kostenFaktor;

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual Held Held
        {
            get { return _held; }
            set
            {
                if (!ReferenceEquals(_held, value))
                {
                    var previousValue = _held;
                    _held = value;
                    FixupHeld(previousValue);
                }
            }
        }
        private Held _held;
    
    	[DataMember]
        public virtual VorNachteil VorNachteil
        {
            get { return _vorNachteil; }
            set
            {
                if (!ReferenceEquals(_vorNachteil, value))
                {
                    var previousValue = _vorNachteil;
                    _vorNachteil = value;
                    FixupVorNachteil(previousValue);
                }
            }
        }
        private VorNachteil _vorNachteil;

        #endregion

        #region Association Fixup
    
        private void FixupHeld(Held previousValue)
        {
    		OnChanged("Held");
            if (previousValue != null && previousValue.Held_VorNachteil.Contains(this))
            {
                previousValue.Held_VorNachteil.Remove(this);
            }
    
            if (Held != null)
            {
                if (!Held.Held_VorNachteil.Contains(this))
                {
                    Held.Held_VorNachteil.Add(this);
                }
                if (HeldGUID != Held.HeldGUID)
                {
                    HeldGUID = Held.HeldGUID;
                }
            }
        }
    
        private void FixupVorNachteil(VorNachteil previousValue)
        {
    		OnChanged("VorNachteil");
            if (previousValue != null && previousValue.Held_VorNachteil.Contains(this))
            {
                previousValue.Held_VorNachteil.Remove(this);
            }
    
            if (VorNachteil != null)
            {
                if (!VorNachteil.Held_VorNachteil.Contains(this))
                {
                    VorNachteil.Held_VorNachteil.Add(this);
                }
                if (VorNachteilGUID != VorNachteil.VorNachteilGUID)
                {
                    VorNachteilGUID = VorNachteil.VorNachteilGUID;
                }
            }
        }

        #endregion

    }
}
