//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace MeisterGeister.Model
{
    [DataContract(IsReference=true)]
    public partial class Held_BFAusrüstung : INotifyPropertyChanged
    {
        #region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    	
    	/// <summary>
        /// Notifies listeners that a property value has changed.
        /// </summary>
        /// <param name="propertyName">Name of the property used to notify listeners.  This
        /// value is optional and can be provided automatically when invoked from compilers
        /// that support <see cref="CallerMemberNameAttribute"/>.</param>
        protected void OnChanged([CallerMemberName] string propertyName = null)
        {
            var eventHandler = this.PropertyChanged;
            if (eventHandler != null)
            {
                eventHandler(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        #endregion

        #region ValidatePropertyChanging
    	protected event Extensions.ValidatePropertyChangingEventHandler ValidatePropertyChanging;
    
    	protected void OnValidatePropertyChanging(object currentValue, object newValue, [CallerMemberName] string propertyName = null)
    	{
    		if(ValidatePropertyChanging != null)
    		{
    			ValidatePropertyChanging(this, propertyName, currentValue, newValue);
    		}
    	}

        #endregion

        #region Set
    	/// <summary>
        /// Checks if a property already matches a desired value.  Sets the property and
        /// notifies listeners only when necessary.
        /// </summary>
        /// <typeparam name="T">Type of the property.</typeparam>
        /// <param name="storage">Reference to a property with both getter and setter.</param>
        /// <param name="value">Desired value for the property.</param>
        /// <param name="propertyName">Name of the property used to notify listeners.  This
        /// value is optional and can be provided automatically when invoked from compilers that
        /// support CallerMemberName.</param>
        /// <returns>True if the value was changed, false if the existing value matched the
        /// desired value.</returns>
        protected bool Set<T>(ref T storage, T value, [CallerMemberName] String propertyName = null)
        {
            if (object.Equals(storage, value)) return false;
    
    		OnValidatePropertyChanging(storage, value, propertyName);
    		storage = value;
    		OnChanged(propertyName);
            return true;
        }

        #endregion

        #region Primitive Properties
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid HeldAusrüstungGUID
        {
            get { return _heldAusrüstungGUID; }
            set
            {
                if (_heldAusrüstungGUID != value)
                {
                    if (Held_Ausrüstung != null && Held_Ausrüstung.HeldAusrüstungGUID != value)
                    {
                        Held_Ausrüstung = null;
                    }
                    _heldAusrüstungGUID = value;
                }
            }
    
        }
        private System.Guid _heldAusrüstungGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int BF
        {
            get { return _bF; }
            set
    		{ 
    			Set(ref _bF, value);
    		}
    
        }
        private int _bF;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int StartBF
        {
            get { return _startBF; }
            set
    		{ 
    			Set(ref _startBF, value);
    		}
    
        }
        private int _startBF;

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual Held_Ausrüstung Held_Ausrüstung
        {
            get { return _held_Ausrüstung; }
            set
            {
                if (!ReferenceEquals(_held_Ausrüstung, value))
                {
                    var previousValue = _held_Ausrüstung;
                    _held_Ausrüstung = value;
                    FixupHeld_Ausrüstung(previousValue);
                }
            }
        }
        private Held_Ausrüstung _held_Ausrüstung;
    
    	[DataMember]
        public virtual Held_Waffe Held_Waffe
        {
            get { return _held_Waffe; }
            set
            {
                if (!ReferenceEquals(_held_Waffe, value))
                {
                    var previousValue = _held_Waffe;
                    _held_Waffe = value;
                    FixupHeld_Waffe(previousValue);
                }
            }
        }
        private Held_Waffe _held_Waffe;
    
    	[DataMember]
        public virtual Schild Schild
        {
            get { return _schild; }
            set
            {
                if (!ReferenceEquals(_schild, value))
                {
                    var previousValue = _schild;
                    _schild = value;
                    FixupSchild(previousValue);
                }
            }
        }
        private Schild _schild;

        #endregion

        #region Association Fixup
    
        private void FixupHeld_Ausrüstung(Held_Ausrüstung previousValue)
        {
    		OnChanged("Held_Ausrüstung");
            if (previousValue != null && ReferenceEquals(previousValue.Held_BFAusrüstung, this))
            {
                previousValue.Held_BFAusrüstung = null;
            }
    
            if (Held_Ausrüstung != null)
            {
                Held_Ausrüstung.Held_BFAusrüstung = this;
                if (HeldAusrüstungGUID != Held_Ausrüstung.HeldAusrüstungGUID)
                {
                    HeldAusrüstungGUID = Held_Ausrüstung.HeldAusrüstungGUID;
                }
            }
        }
    
        private void FixupHeld_Waffe(Held_Waffe previousValue)
        {
    		OnChanged("Held_Waffe");
            if (previousValue != null && ReferenceEquals(previousValue.Held_BFAusrüstung, this))
            {
                previousValue.Held_BFAusrüstung = null;
            }
    
            if (Held_Waffe != null)
            {
                Held_Waffe.Held_BFAusrüstung = this;
            }
        }
    
        private void FixupSchild(Schild previousValue)
        {
    		OnChanged("Schild");
            if (previousValue != null && previousValue.Held_BFAusrüstung.Contains(this))
            {
                previousValue.Held_BFAusrüstung.Remove(this);
            }
    
            if (Schild != null)
            {
                if (!Schild.Held_BFAusrüstung.Contains(this))
                {
                    Schild.Held_BFAusrüstung.Add(this);
                }
            }
        }

        #endregion

    }
}
