//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel;

namespace MeisterGeister.Model
{
    [DataContract(IsReference=true)]
    public partial class Held : INotifyPropertyChanged
    {
        #region ValidatePropertyChanging
    	protected event Extensions.ValidatePropertyChangingEventHandler ValidatePropertyChanging;
    
    	protected void OnValidatePropertyChanging(String propertyName, object currentValue, object newValue)
    	{
    		if(ValidatePropertyChanging != null)
    		{
    			ValidatePropertyChanging(this, propertyName, currentValue, newValue);
    		}
    	}

        #endregion

        #region Primitive Properties
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Name
        {
            get { return _name; }
            set
    		{ 
    			OnValidatePropertyChanging("Name",_name, value);
    			_name = value;
    			OnChanged("Name");
    		}
    
        }
        private string _name;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> MU
        {
            get { return _mU; }
            set
    		{ 
    			OnValidatePropertyChanging("MU",_mU, value);
    			_mU = value;
    			OnChanged("MU");
    		}
    
        }
        private Nullable<int> _mU;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> KL
        {
            get { return _kL; }
            set
    		{ 
    			OnValidatePropertyChanging("KL",_kL, value);
    			_kL = value;
    			OnChanged("KL");
    		}
    
        }
        private Nullable<int> _kL;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> IN
        {
            get { return _iN; }
            set
    		{ 
    			OnValidatePropertyChanging("IN",_iN, value);
    			_iN = value;
    			OnChanged("IN");
    		}
    
        }
        private Nullable<int> _iN;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> CH
        {
            get { return _cH; }
            set
    		{ 
    			OnValidatePropertyChanging("CH",_cH, value);
    			_cH = value;
    			OnChanged("CH");
    		}
    
        }
        private Nullable<int> _cH;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> FF
        {
            get { return _fF; }
            set
    		{ 
    			OnValidatePropertyChanging("FF",_fF, value);
    			_fF = value;
    			OnChanged("FF");
    		}
    
        }
        private Nullable<int> _fF;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> GE
        {
            get { return _gE; }
            set
    		{ 
    			OnValidatePropertyChanging("GE",_gE, value);
    			_gE = value;
    			OnChanged("GE");
    		}
    
        }
        private Nullable<int> _gE;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> KO
        {
            get { return _kO; }
            set
    		{ 
    			OnValidatePropertyChanging("KO",_kO, value);
    			_kO = value;
    			OnChanged("KO");
    		}
    
        }
        private Nullable<int> _kO;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> KK
        {
            get { return _kK; }
            set
    		{ 
    			OnValidatePropertyChanging("KK",_kK, value);
    			_kK = value;
    			OnChanged("KK");
    		}
    
        }
        private Nullable<int> _kK;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> BE
        {
            get { return _bE; }
            set
    		{ 
    			OnValidatePropertyChanging("BE",_bE, value);
    			_bE = value;
    			OnChanged("BE");
    		}
    
        }
        private Nullable<int> _bE;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> INI_Mod
        {
            get { return _iNI_Mod; }
            set
    		{ 
    			OnValidatePropertyChanging("INI_Mod",_iNI_Mod, value);
    			_iNI_Mod = value;
    			OnChanged("INI_Mod");
    		}
    
        }
        private Nullable<int> _iNI_Mod;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> LE_Mod
        {
            get { return _lE_Mod; }
            set
    		{ 
    			OnValidatePropertyChanging("LE_Mod",_lE_Mod, value);
    			_lE_Mod = value;
    			OnChanged("LE_Mod");
    		}
    
        }
        private Nullable<int> _lE_Mod;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> LE_Aktuell
        {
            get { return _lE_Aktuell; }
            set
    		{ 
    			OnValidatePropertyChanging("LE_Aktuell",_lE_Aktuell, value);
    			_lE_Aktuell = value;
    			OnChanged("LE_Aktuell");
    		}
    
        }
        private Nullable<int> _lE_Aktuell;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> AU_Mod
        {
            get { return _aU_Mod; }
            set
    		{ 
    			OnValidatePropertyChanging("AU_Mod",_aU_Mod, value);
    			_aU_Mod = value;
    			OnChanged("AU_Mod");
    		}
    
        }
        private Nullable<int> _aU_Mod;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> AU_Aktuell
        {
            get { return _aU_Aktuell; }
            set
    		{ 
    			OnValidatePropertyChanging("AU_Aktuell",_aU_Aktuell, value);
    			_aU_Aktuell = value;
    			OnChanged("AU_Aktuell");
    		}
    
        }
        private Nullable<int> _aU_Aktuell;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> AE_Mod
        {
            get { return _aE_Mod; }
            set
    		{ 
    			OnValidatePropertyChanging("AE_Mod",_aE_Mod, value);
    			_aE_Mod = value;
    			OnChanged("AE_Mod");
    		}
    
        }
        private Nullable<int> _aE_Mod;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> AE_Aktuell
        {
            get { return _aE_Aktuell; }
            set
    		{ 
    			OnValidatePropertyChanging("AE_Aktuell",_aE_Aktuell, value);
    			_aE_Aktuell = value;
    			OnChanged("AE_Aktuell");
    		}
    
        }
        private Nullable<int> _aE_Aktuell;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> KE_Mod
        {
            get { return _kE_Mod; }
            set
    		{ 
    			OnValidatePropertyChanging("KE_Mod",_kE_Mod, value);
    			_kE_Mod = value;
    			OnChanged("KE_Mod");
    		}
    
        }
        private Nullable<int> _kE_Mod;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> KE_Aktuell
        {
            get { return _kE_Aktuell; }
            set
    		{ 
    			OnValidatePropertyChanging("KE_Aktuell",_kE_Aktuell, value);
    			_kE_Aktuell = value;
    			OnChanged("KE_Aktuell");
    		}
    
        }
        private Nullable<int> _kE_Aktuell;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> MR_Mod
        {
            get { return _mR_Mod; }
            set
    		{ 
    			OnValidatePropertyChanging("MR_Mod",_mR_Mod, value);
    			_mR_Mod = value;
    			OnChanged("MR_Mod");
    		}
    
        }
        private Nullable<int> _mR_Mod;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Kampfwerte
        {
            get { return _kampfwerte; }
            set
    		{ 
    			OnValidatePropertyChanging("Kampfwerte",_kampfwerte, value);
    			_kampfwerte = value;
    			OnChanged("Kampfwerte");
    		}
    
        }
        private string _kampfwerte;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> Wunden
        {
            get { return _wunden; }
            set
    		{ 
    			OnValidatePropertyChanging("Wunden",_wunden, value);
    			_wunden = value;
    			OnChanged("Wunden");
    		}
    
        }
        private Nullable<int> _wunden;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<bool> AktiveHeldengruppe
        {
            get { return _aktiveHeldengruppe; }
            set
    		{ 
    			OnValidatePropertyChanging("AktiveHeldengruppe",_aktiveHeldengruppe, value);
    			_aktiveHeldengruppe = value;
    			OnChanged("AktiveHeldengruppe");
    		}
    
        }
        private Nullable<bool> _aktiveHeldengruppe;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<bool> Proben
        {
            get { return _proben; }
            set
    		{ 
    			OnValidatePropertyChanging("Proben",_proben, value);
    			_proben = value;
    			OnChanged("Proben");
    		}
    
        }
        private Nullable<bool> _proben;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Rasse
        {
            get { return _rasse; }
            set
    		{ 
    			OnValidatePropertyChanging("Rasse",_rasse, value);
    			_rasse = value;
    			OnChanged("Rasse");
    		}
    
        }
        private string _rasse;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Kultur
        {
            get { return _kultur; }
            set
    		{ 
    			OnValidatePropertyChanging("Kultur",_kultur, value);
    			_kultur = value;
    			OnChanged("Kultur");
    		}
    
        }
        private string _kultur;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Profession
        {
            get { return _profession; }
            set
    		{ 
    			OnValidatePropertyChanging("Profession",_profession, value);
    			_profession = value;
    			OnChanged("Profession");
    		}
    
        }
        private string _profession;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Notizen
        {
            get { return _notizen; }
            set
    		{ 
    			OnValidatePropertyChanging("Notizen",_notizen, value);
    			_notizen = value;
    			OnChanged("Notizen");
    		}
    
        }
        private string _notizen;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int WundenKopf
        {
            get { return _wundenKopf; }
            set
    		{ 
    			OnValidatePropertyChanging("WundenKopf",_wundenKopf, value);
    			_wundenKopf = value;
    			OnChanged("WundenKopf");
    		}
    
        }
        private int _wundenKopf;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int WundenBrust
        {
            get { return _wundenBrust; }
            set
    		{ 
    			OnValidatePropertyChanging("WundenBrust",_wundenBrust, value);
    			_wundenBrust = value;
    			OnChanged("WundenBrust");
    		}
    
        }
        private int _wundenBrust;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int WundenArmL
        {
            get { return _wundenArmL; }
            set
    		{ 
    			OnValidatePropertyChanging("WundenArmL",_wundenArmL, value);
    			_wundenArmL = value;
    			OnChanged("WundenArmL");
    		}
    
        }
        private int _wundenArmL;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int WundenArmR
        {
            get { return _wundenArmR; }
            set
    		{ 
    			OnValidatePropertyChanging("WundenArmR",_wundenArmR, value);
    			_wundenArmR = value;
    			OnChanged("WundenArmR");
    		}
    
        }
        private int _wundenArmR;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int WundenBauch
        {
            get { return _wundenBauch; }
            set
    		{ 
    			OnValidatePropertyChanging("WundenBauch",_wundenBauch, value);
    			_wundenBauch = value;
    			OnChanged("WundenBauch");
    		}
    
        }
        private int _wundenBauch;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int WundenBeinL
        {
            get { return _wundenBeinL; }
            set
    		{ 
    			OnValidatePropertyChanging("WundenBeinL",_wundenBeinL, value);
    			_wundenBeinL = value;
    			OnChanged("WundenBeinL");
    		}
    
        }
        private int _wundenBeinL;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int WundenBeinR
        {
            get { return _wundenBeinR; }
            set
    		{ 
    			OnValidatePropertyChanging("WundenBeinR",_wundenBeinR, value);
    			_wundenBeinR = value;
    			OnChanged("WundenBeinR");
    		}
    
        }
        private int _wundenBeinR;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int RSKopf
        {
            get { return _rSKopf; }
            set
    		{ 
    			OnValidatePropertyChanging("RSKopf",_rSKopf, value);
    			_rSKopf = value;
    			OnChanged("RSKopf");
    		}
    
        }
        private int _rSKopf;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int RSBrust
        {
            get { return _rSBrust; }
            set
    		{ 
    			OnValidatePropertyChanging("RSBrust",_rSBrust, value);
    			_rSBrust = value;
    			OnChanged("RSBrust");
    		}
    
        }
        private int _rSBrust;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int RSRücken
        {
            get { return _rSRücken; }
            set
    		{ 
    			OnValidatePropertyChanging("RSRücken",_rSRücken, value);
    			_rSRücken = value;
    			OnChanged("RSRücken");
    		}
    
        }
        private int _rSRücken;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int RSArmL
        {
            get { return _rSArmL; }
            set
    		{ 
    			OnValidatePropertyChanging("RSArmL",_rSArmL, value);
    			_rSArmL = value;
    			OnChanged("RSArmL");
    		}
    
        }
        private int _rSArmL;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int RSArmR
        {
            get { return _rSArmR; }
            set
    		{ 
    			OnValidatePropertyChanging("RSArmR",_rSArmR, value);
    			_rSArmR = value;
    			OnChanged("RSArmR");
    		}
    
        }
        private int _rSArmR;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int RSBauch
        {
            get { return _rSBauch; }
            set
    		{ 
    			OnValidatePropertyChanging("RSBauch",_rSBauch, value);
    			_rSBauch = value;
    			OnChanged("RSBauch");
    		}
    
        }
        private int _rSBauch;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int RSBeinL
        {
            get { return _rSBeinL; }
            set
    		{ 
    			OnValidatePropertyChanging("RSBeinL",_rSBeinL, value);
    			_rSBeinL = value;
    			OnChanged("RSBeinL");
    		}
    
        }
        private int _rSBeinL;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int RSBeinR
        {
            get { return _rSBeinR; }
            set
    		{ 
    			OnValidatePropertyChanging("RSBeinR",_rSBeinR, value);
    			_rSBeinR = value;
    			OnChanged("RSBeinR");
    		}
    
        }
        private int _rSBeinR;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> SO
        {
            get { return _sO; }
            set
    		{ 
    			OnValidatePropertyChanging("SO",_sO, value);
    			_sO = value;
    			OnChanged("SO");
    		}
    
        }
        private Nullable<int> _sO;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid HeldGUID
        {
            get { return _heldGUID; }
            set
    		{ 
    			OnValidatePropertyChanging("HeldGUID",_heldGUID, value);
    			_heldGUID = value;
    			OnChanged("HeldGUID");
    		}
    
        }
        private System.Guid _heldGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Bild
        {
            get { return _bild; }
            set
    		{ 
    			OnValidatePropertyChanging("Bild",_bild, value);
    			_bild = value;
    			OnChanged("Bild");
    		}
    
        }
        private string _bild;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Spieler
        {
            get { return _spieler; }
            set
    		{ 
    			OnValidatePropertyChanging("Spieler",_spieler, value);
    			_spieler = value;
    			OnChanged("Spieler");
    		}
    
        }
        private string _spieler;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<double> Vermögen
        {
            get { return _vermögen; }
            set
    		{ 
    			OnValidatePropertyChanging("Vermögen",_vermögen, value);
    			_vermögen = value;
    			OnChanged("Vermögen");
    		}
    
        }
        private Nullable<double> _vermögen;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> APGesamt
        {
            get { return _aPGesamt; }
            set
    		{ 
    			OnValidatePropertyChanging("APGesamt",_aPGesamt, value);
    			_aPGesamt = value;
    			OnChanged("APGesamt");
    		}
    
        }
        private Nullable<int> _aPGesamt;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> APEingesetzt
        {
            get { return _aPEingesetzt; }
            set
    		{ 
    			OnValidatePropertyChanging("APEingesetzt",_aPEingesetzt, value);
    			_aPEingesetzt = value;
    			OnChanged("APEingesetzt");
    		}
    
        }
        private Nullable<int> _aPEingesetzt;

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual ICollection<Held_Ausrüstung> Held_Ausrüstung
        {
            get
            {
                if (_held_Ausrüstung == null)
                {
                    var newCollection = new FixupCollection<Held_Ausrüstung>();
                    newCollection.CollectionChanged += FixupHeld_Ausrüstung;
                    _held_Ausrüstung = newCollection;
                }
                return _held_Ausrüstung;
            }
            set
            {
                if (!ReferenceEquals(_held_Ausrüstung, value))
                {
                    var previousValue = _held_Ausrüstung as FixupCollection<Held_Ausrüstung>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupHeld_Ausrüstung;
                    }
                    _held_Ausrüstung = value;
                    var newValue = value as FixupCollection<Held_Ausrüstung>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupHeld_Ausrüstung;
                    }
                }
            }
        }
        private ICollection<Held_Ausrüstung> _held_Ausrüstung;
    
    	[DataMember]
        public virtual ICollection<Held_Inventar> Held_Inventar
        {
            get
            {
                if (_held_Inventar == null)
                {
                    var newCollection = new FixupCollection<Held_Inventar>();
                    newCollection.CollectionChanged += FixupHeld_Inventar;
                    _held_Inventar = newCollection;
                }
                return _held_Inventar;
            }
            set
            {
                if (!ReferenceEquals(_held_Inventar, value))
                {
                    var previousValue = _held_Inventar as FixupCollection<Held_Inventar>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupHeld_Inventar;
                    }
                    _held_Inventar = value;
                    var newValue = value as FixupCollection<Held_Inventar>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupHeld_Inventar;
                    }
                }
            }
        }
        private ICollection<Held_Inventar> _held_Inventar;
    
    	[DataMember]
        public virtual ICollection<Held_Munition> Held_Munition
        {
            get
            {
                if (_held_Munition == null)
                {
                    var newCollection = new FixupCollection<Held_Munition>();
                    newCollection.CollectionChanged += FixupHeld_Munition;
                    _held_Munition = newCollection;
                }
                return _held_Munition;
            }
            set
            {
                if (!ReferenceEquals(_held_Munition, value))
                {
                    var previousValue = _held_Munition as FixupCollection<Held_Munition>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupHeld_Munition;
                    }
                    _held_Munition = value;
                    var newValue = value as FixupCollection<Held_Munition>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupHeld_Munition;
                    }
                }
            }
        }
        private ICollection<Held_Munition> _held_Munition;
    
    	[DataMember]
        public virtual ICollection<Held_Talent> Held_Talent
        {
            get
            {
                if (_held_Talent == null)
                {
                    var newCollection = new FixupCollection<Held_Talent>();
                    newCollection.CollectionChanged += FixupHeld_Talent;
                    _held_Talent = newCollection;
                }
                return _held_Talent;
            }
            set
            {
                if (!ReferenceEquals(_held_Talent, value))
                {
                    var previousValue = _held_Talent as FixupCollection<Held_Talent>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupHeld_Talent;
                    }
                    _held_Talent = value;
                    var newValue = value as FixupCollection<Held_Talent>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupHeld_Talent;
                    }
                }
            }
        }
        private ICollection<Held_Talent> _held_Talent;
    
    	[DataMember]
        public virtual ICollection<Held_Sonderfertigkeit> Held_Sonderfertigkeit
        {
            get
            {
                if (_held_Sonderfertigkeit == null)
                {
                    var newCollection = new FixupCollection<Held_Sonderfertigkeit>();
                    newCollection.CollectionChanged += FixupHeld_Sonderfertigkeit;
                    _held_Sonderfertigkeit = newCollection;
                }
                return _held_Sonderfertigkeit;
            }
            set
            {
                if (!ReferenceEquals(_held_Sonderfertigkeit, value))
                {
                    var previousValue = _held_Sonderfertigkeit as FixupCollection<Held_Sonderfertigkeit>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupHeld_Sonderfertigkeit;
                    }
                    _held_Sonderfertigkeit = value;
                    var newValue = value as FixupCollection<Held_Sonderfertigkeit>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupHeld_Sonderfertigkeit;
                    }
                }
            }
        }
        private ICollection<Held_Sonderfertigkeit> _held_Sonderfertigkeit;
    
    	[DataMember]
        public virtual ICollection<Held_VorNachteil> Held_VorNachteil
        {
            get
            {
                if (_held_VorNachteil == null)
                {
                    var newCollection = new FixupCollection<Held_VorNachteil>();
                    newCollection.CollectionChanged += FixupHeld_VorNachteil;
                    _held_VorNachteil = newCollection;
                }
                return _held_VorNachteil;
            }
            set
            {
                if (!ReferenceEquals(_held_VorNachteil, value))
                {
                    var previousValue = _held_VorNachteil as FixupCollection<Held_VorNachteil>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupHeld_VorNachteil;
                    }
                    _held_VorNachteil = value;
                    var newValue = value as FixupCollection<Held_VorNachteil>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupHeld_VorNachteil;
                    }
                }
            }
        }
        private ICollection<Held_VorNachteil> _held_VorNachteil;
    
    	[DataMember]
        public virtual ICollection<Held_Zauber> Held_Zauber
        {
            get
            {
                if (_held_Zauber == null)
                {
                    var newCollection = new FixupCollection<Held_Zauber>();
                    newCollection.CollectionChanged += FixupHeld_Zauber;
                    _held_Zauber = newCollection;
                }
                return _held_Zauber;
            }
            set
            {
                if (!ReferenceEquals(_held_Zauber, value))
                {
                    var previousValue = _held_Zauber as FixupCollection<Held_Zauber>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupHeld_Zauber;
                    }
                    _held_Zauber = value;
                    var newValue = value as FixupCollection<Held_Zauber>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupHeld_Zauber;
                    }
                }
            }
        }
        private ICollection<Held_Zauber> _held_Zauber;

        #endregion

        #region Association Fixup
    
        private void FixupHeld_Ausrüstung(object sender, NotifyCollectionChangedEventArgs e)
        {
    		OnChanged("Held_Ausrüstung");
            if (e.NewItems != null)
            {
                foreach (Held_Ausrüstung item in e.NewItems)
                {
                    item.Held = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Held_Ausrüstung item in e.OldItems)
                {
                    if (ReferenceEquals(item.Held, this))
                    {
                        item.Held = null;
                    }
                }
            }
        }
    
        private void FixupHeld_Inventar(object sender, NotifyCollectionChangedEventArgs e)
        {
    		OnChanged("Held_Inventar");
            if (e.NewItems != null)
            {
                foreach (Held_Inventar item in e.NewItems)
                {
                    item.Held = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Held_Inventar item in e.OldItems)
                {
                    if (ReferenceEquals(item.Held, this))
                    {
                        item.Held = null;
                    }
                }
            }
        }
    
        private void FixupHeld_Munition(object sender, NotifyCollectionChangedEventArgs e)
        {
    		OnChanged("Held_Munition");
            if (e.NewItems != null)
            {
                foreach (Held_Munition item in e.NewItems)
                {
                    item.Held = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Held_Munition item in e.OldItems)
                {
                    if (ReferenceEquals(item.Held, this))
                    {
                        item.Held = null;
                    }
                }
            }
        }
    
        private void FixupHeld_Talent(object sender, NotifyCollectionChangedEventArgs e)
        {
    		OnChanged("Held_Talent");
            if (e.NewItems != null)
            {
                foreach (Held_Talent item in e.NewItems)
                {
                    item.Held = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Held_Talent item in e.OldItems)
                {
                    if (ReferenceEquals(item.Held, this))
                    {
                        item.Held = null;
                    }
                }
            }
        }
    
        private void FixupHeld_Sonderfertigkeit(object sender, NotifyCollectionChangedEventArgs e)
        {
    		OnChanged("Held_Sonderfertigkeit");
            if (e.NewItems != null)
            {
                foreach (Held_Sonderfertigkeit item in e.NewItems)
                {
                    item.Held = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Held_Sonderfertigkeit item in e.OldItems)
                {
                    if (ReferenceEquals(item.Held, this))
                    {
                        item.Held = null;
                    }
                }
            }
        }
    
        private void FixupHeld_VorNachteil(object sender, NotifyCollectionChangedEventArgs e)
        {
    		OnChanged("Held_VorNachteil");
            if (e.NewItems != null)
            {
                foreach (Held_VorNachteil item in e.NewItems)
                {
                    item.Held = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Held_VorNachteil item in e.OldItems)
                {
                    if (ReferenceEquals(item.Held, this))
                    {
                        item.Held = null;
                    }
                }
            }
        }
    
        private void FixupHeld_Zauber(object sender, NotifyCollectionChangedEventArgs e)
        {
    		OnChanged("Held_Zauber");
            if (e.NewItems != null)
            {
                foreach (Held_Zauber item in e.NewItems)
                {
                    item.Held = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Held_Zauber item in e.OldItems)
                {
                    if (ReferenceEquals(item.Held, this))
                    {
                        item.Held = null;
                    }
                }
            }
        }

        #endregion

    }
}
