//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel;

namespace MeisterGeister.Model
{
    [DataContract(IsReference=true)]
    public partial class Held_Inventar : INotifyPropertyChanged
    {
        #region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    	
    	public void OnChanged(String info)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(info));
            }
        }

        #endregion
        #region Primitive Properties
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid HeldGUID
        {
            get { return _heldGUID; }
            set
            {
                if (_heldGUID != value)
                {
                    if (Held != null && Held.HeldGUID != value)
                    {
                        Held = null;
                    }
                    _heldGUID = value;
                }
            }
    
        }
        private System.Guid _heldGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual bool Angelegt
        {
            get { return _angelegt; }
            set
    		{ 
    			_angelegt = value;
    			OnChanged("Angelegt");
    		}
    
        }
        private bool _angelegt;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Ort
        {
            get { return _ort; }
            set
    		{ 
    			_ort = value;
    			OnChanged("Ort");
    		}
    
        }
        private string _ort;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid InventarGUID
        {
            get { return _inventarGUID; }
            set
            {
                if (_inventarGUID != value)
                {
                    if (Inventar != null && Inventar.InventarGUID != value)
                    {
                        Inventar = null;
                    }
                    _inventarGUID = value;
                }
            }
    
        }
        private System.Guid _inventarGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> Anzahl
        {
            get { return _anzahl; }
            set
    		{ 
    			_anzahl = value;
    			OnChanged("Anzahl");
    		}
    
        }
        private Nullable<int> _anzahl;

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual Held Held
        {
            get { return _held; }
            set
            {
                if (!ReferenceEquals(_held, value))
                {
                    var previousValue = _held;
                    _held = value;
                    FixupHeld(previousValue);
                }
            }
        }
        private Held _held;
    
    	[DataMember]
        public virtual Inventar Inventar
        {
            get { return _inventar; }
            set
            {
                if (!ReferenceEquals(_inventar, value))
                {
                    var previousValue = _inventar;
                    _inventar = value;
                    FixupInventar(previousValue);
                }
            }
        }
        private Inventar _inventar;

        #endregion
        #region Association Fixup
    
        private void FixupHeld(Held previousValue)
        {
    		OnChanged("Held");
            if (previousValue != null && previousValue.Held_Inventar.Contains(this))
            {
                previousValue.Held_Inventar.Remove(this);
            }
    
            if (Held != null)
            {
                if (!Held.Held_Inventar.Contains(this))
                {
                    Held.Held_Inventar.Add(this);
                }
                if (HeldGUID != Held.HeldGUID)
                {
                    HeldGUID = Held.HeldGUID;
                }
            }
        }
    
        private void FixupInventar(Inventar previousValue)
        {
    		OnChanged("Inventar");
            if (previousValue != null && previousValue.Held_Inventar.Contains(this))
            {
                previousValue.Held_Inventar.Remove(this);
            }
    
            if (Inventar != null)
            {
                if (!Inventar.Held_Inventar.Contains(this))
                {
                    Inventar.Held_Inventar.Add(this);
                }
                if (InventarGUID != Inventar.InventarGUID)
                {
                    InventarGUID = Inventar.InventarGUID;
                }
            }
        }

        #endregion
    }
}
