//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel;

namespace MeisterGeister.Model
{
    [DataContract(IsReference=true)]
    public partial class Held_VorNachteil : INotifyPropertyChanged
    {
        #region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    	
    	public void OnChanged(String info)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(info));
            }
        }

        #endregion

        #region ValidatePropertyChanging
    	protected event Extensions.ValidatePropertyChangingEventHandler ValidatePropertyChanging;
    
    	protected void OnValidatePropertyChanging(String propertyName, object currentValue, object newValue)
    	{
    		if(ValidatePropertyChanging != null)
    		{
    			ValidatePropertyChanging(this, propertyName, currentValue, newValue);
    		}
    	}

        #endregion

        #region Primitive Properties
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid HeldGUID
        {
            get { return _heldGUID; }
            set
            {
                if (_heldGUID != value)
                {
                    if (Held != null && Held.HeldGUID != value)
                    {
                        Held = null;
                    }
                    _heldGUID = value;
                }
            }
    
        }
        private System.Guid _heldGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid VorNachteilGUID
        {
            get { return _vorNachteilGUID; }
            set
            {
                if (_vorNachteilGUID != value)
                {
                    if (VorNachteil != null && VorNachteil.VorNachteilGUID != value)
                    {
                        VorNachteil = null;
                    }
                    _vorNachteilGUID = value;
                }
            }
    
        }
        private System.Guid _vorNachteilGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Wert
        {
            get { return _wert; }
            set
    		{ 
    			OnValidatePropertyChanging("Wert",_wert, value);
    			_wert = value;
    			OnChanged("Wert");
    		}
    
        }
        private string _wert;

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual Held Held
        {
            get { return _held; }
            set
            {
                if (!ReferenceEquals(_held, value))
                {
                    var previousValue = _held;
                    _held = value;
                    FixupHeld(previousValue);
                }
            }
        }
        private Held _held;
    
    	[DataMember]
        public virtual VorNachteil VorNachteil
        {
            get { return _vorNachteil; }
            set
            {
                if (!ReferenceEquals(_vorNachteil, value))
                {
                    var previousValue = _vorNachteil;
                    _vorNachteil = value;
                    FixupVorNachteil(previousValue);
                }
            }
        }
        private VorNachteil _vorNachteil;

        #endregion

        #region Association Fixup
    
        private void FixupHeld(Held previousValue)
        {
    		OnChanged("Held");
            if (previousValue != null && previousValue.Held_VorNachteil.Contains(this))
            {
                previousValue.Held_VorNachteil.Remove(this);
            }
    
            if (Held != null)
            {
                if (!Held.Held_VorNachteil.Contains(this))
                {
                    Held.Held_VorNachteil.Add(this);
                }
                if (HeldGUID != Held.HeldGUID)
                {
                    HeldGUID = Held.HeldGUID;
                }
            }
        }
    
        private void FixupVorNachteil(VorNachteil previousValue)
        {
    		OnChanged("VorNachteil");
            if (previousValue != null && previousValue.Held_VorNachteil.Contains(this))
            {
                previousValue.Held_VorNachteil.Remove(this);
            }
    
            if (VorNachteil != null)
            {
                if (!VorNachteil.Held_VorNachteil.Contains(this))
                {
                    VorNachteil.Held_VorNachteil.Add(this);
                }
                if (VorNachteilGUID != VorNachteil.VorNachteilGUID)
                {
                    VorNachteilGUID = VorNachteil.VorNachteilGUID;
                }
            }
        }

        #endregion

    }
}
