//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace MeisterGeister.Model
{
    [DataContract(IsReference=true)]
    public partial class Kultur_Name : INotifyPropertyChanged
    {
        #region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    	
    	/// <summary>
        /// Notifies listeners that a property value has changed.
        /// </summary>
        /// <param name="propertyName">Name of the property used to notify listeners.  This
        /// value is optional and can be provided automatically when invoked from compilers
        /// that support <see cref="CallerMemberNameAttribute"/>.</param>
        protected void OnChanged([CallerMemberName] string propertyName = null)
        {
            var eventHandler = this.PropertyChanged;
            if (eventHandler != null)
            {
                eventHandler(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        #endregion

        #region ValidatePropertyChanging
    	protected event Extensions.ValidatePropertyChangingEventHandler ValidatePropertyChanging;
    
    	protected void OnValidatePropertyChanging(object currentValue, object newValue, [CallerMemberName] string propertyName = null)
    	{
    		if(ValidatePropertyChanging != null)
    		{
    			ValidatePropertyChanging(this, propertyName, currentValue, newValue);
    		}
    	}

        #endregion

        #region Set
    	/// <summary>
        /// Checks if a property already matches a desired value.  Sets the property and
        /// notifies listeners only when necessary.
        /// </summary>
        /// <typeparam name="T">Type of the property.</typeparam>
        /// <param name="storage">Reference to a property with both getter and setter.</param>
        /// <param name="value">Desired value for the property.</param>
        /// <param name="propertyName">Name of the property used to notify listeners.  This
        /// value is optional and can be provided automatically when invoked from compilers that
        /// support CallerMemberName.</param>
        /// <returns>True if the value was changed, false if the existing value matched the
        /// desired value.</returns>
        protected bool Set<T>(ref T storage, T value, [CallerMemberName] String propertyName = null)
        {
            if (object.Equals(storage, value)) return false;
    
    		OnValidatePropertyChanging(storage, value, propertyName);
    		storage = value;
    		OnChanged(propertyName);
            return true;
        }

        #endregion

        #region Primitive Properties
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid KulturGUID
        {
            get { return _kulturGUID; }
            set
            {
                if (_kulturGUID != value)
                {
                    if (Kultur != null && Kultur.KulturGUID != value)
                    {
                        Kultur = null;
                    }
                    _kulturGUID = value;
                }
            }
    
        }
        private System.Guid _kulturGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Herkunft
        {
            get { return _herkunft; }
            set
    		{ 
    			Set(ref _herkunft, value);
    		}
    
        }
        private string _herkunft;

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual Kultur Kultur
        {
            get { return _kultur; }
            set
            {
                if (!ReferenceEquals(_kultur, value))
                {
                    var previousValue = _kultur;
                    _kultur = value;
                    FixupKultur(previousValue);
                }
            }
        }
        private Kultur _kultur;

        #endregion

        #region Association Fixup
    
        private void FixupKultur(Kultur previousValue)
        {
    		OnChanged("Kultur");
            if (previousValue != null && previousValue.Kultur_Name.Contains(this))
            {
                previousValue.Kultur_Name.Remove(this);
            }
    
            if (Kultur != null)
            {
                if (!Kultur.Kultur_Name.Contains(this))
                {
                    Kultur.Kultur_Name.Add(this);
                }
                if (KulturGUID != Kultur.KulturGUID)
                {
                    KulturGUID = Kultur.KulturGUID;
                }
            }
        }

        #endregion

    }
}
