//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel;

namespace MeisterGeister.Model
{
    [DataContract(IsReference=true)]
    public partial class Literatur : INotifyPropertyChanged
    {
        #region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    	
    	public void OnChanged(String info)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(info));
            }
        }

        #endregion

        #region ValidatePropertyChanging
    	protected event Extensions.ValidatePropertyChangingEventHandler ValidatePropertyChanging;
    
    	protected void OnValidatePropertyChanging(String propertyName, object currentValue, object newValue)
    	{
    		if(ValidatePropertyChanging != null)
    		{
    			ValidatePropertyChanging(this, propertyName, currentValue, newValue);
    		}
    	}

        #endregion

        #region Primitive Properties
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid LiteraturGUID
        {
            get { return _literaturGUID; }
            set
    		{ 
    			OnValidatePropertyChanging("LiteraturGUID",_literaturGUID, value);
    			_literaturGUID = value;
    			OnChanged("LiteraturGUID");
    		}
    
        }
        private System.Guid _literaturGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Name
        {
            get { return _name; }
            set
    		{ 
    			OnValidatePropertyChanging("Name",_name, value);
    			_name = value;
    			OnChanged("Name");
    		}
    
        }
        private string _name;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Abkürzung
        {
            get { return _abkürzung; }
            set
    		{ 
    			OnValidatePropertyChanging("Abkürzung",_abkürzung, value);
    			_abkürzung = value;
    			OnChanged("Abkürzung");
    		}
    
        }
        private string _abkürzung;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Pfad
        {
            get { return _pfad; }
            set
    		{ 
    			OnValidatePropertyChanging("Pfad",_pfad, value);
    			_pfad = value;
    			OnChanged("Pfad");
    		}
    
        }
        private string _pfad;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int Seitenoffset
        {
            get { return _seitenoffset; }
            set
    		{ 
    			OnValidatePropertyChanging("Seitenoffset",_seitenoffset, value);
    			_seitenoffset = value;
    			OnChanged("Seitenoffset");
    		}
    
        }
        private int _seitenoffset;

        #endregion

    }
}
