//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel;

namespace MeisterGeister.Model
{
    [DataContract(IsReference=true)]
    public partial class MenuLink : INotifyPropertyChanged
    {
        #region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    	
    	public void OnChanged(String info)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(info));
            }
        }

        #endregion

        #region ValidatePropertyChanging
    	protected event Extensions.ValidatePropertyChangingEventHandler ValidatePropertyChanging;
    
    	protected void OnValidatePropertyChanging(String propertyName, object currentValue, object newValue)
    	{
    		if(ValidatePropertyChanging != null)
    		{
    			ValidatePropertyChanging(this, propertyName, currentValue, newValue);
    		}
    	}

        #endregion

        #region Primitive Properties
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string MenuPunkt
        {
            get { return _menuPunkt; }
            set
    		{ 
    			OnValidatePropertyChanging("MenuPunkt",_menuPunkt, value);
    			_menuPunkt = value;
    			OnChanged("MenuPunkt");
    		}
    
        }
        private string _menuPunkt;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string ProgrammPfad
        {
            get { return _programmPfad; }
            set
    		{ 
    			OnValidatePropertyChanging("ProgrammPfad",_programmPfad, value);
    			_programmPfad = value;
    			OnChanged("ProgrammPfad");
    		}
    
        }
        private string _programmPfad;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Name
        {
            get { return _name; }
            set
    		{ 
    			OnValidatePropertyChanging("Name",_name, value);
    			_name = value;
    			OnChanged("Name");
    		}
    
        }
        private string _name;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Bild
        {
            get { return _bild; }
            set
    		{ 
    			OnValidatePropertyChanging("Bild",_bild, value);
    			_bild = value;
    			OnChanged("Bild");
    		}
    
        }
        private string _bild;

        #endregion

    }
}
