//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace MeisterGeister.Model
{
    [DataContract(IsReference=true)]
    public partial class Munition : INotifyPropertyChanged
    {
        #region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    	
    	/// <summary>
        /// Notifies listeners that a property value has changed.
        /// </summary>
        /// <param name="propertyName">Name of the property used to notify listeners.  This
        /// value is optional and can be provided automatically when invoked from compilers
        /// that support <see cref="CallerMemberNameAttribute"/>.</param>
        protected void OnChanged([CallerMemberName] string propertyName = null)
        {
            var eventHandler = this.PropertyChanged;
            if (eventHandler != null)
            {
                eventHandler(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        #endregion

        #region ValidatePropertyChanging
    	protected event Extensions.ValidatePropertyChangingEventHandler ValidatePropertyChanging;
    
    	protected void OnValidatePropertyChanging(object currentValue, object newValue, [CallerMemberName] string propertyName = null)
    	{
    		if(ValidatePropertyChanging != null)
    		{
    			ValidatePropertyChanging(this, propertyName, currentValue, newValue);
    		}
    	}

        #endregion

        #region Set
    	/// <summary>
        /// Checks if a property already matches a desired value.  Sets the property and
        /// notifies listeners only when necessary.
        /// </summary>
        /// <typeparam name="T">Type of the property.</typeparam>
        /// <param name="storage">Reference to a property with both getter and setter.</param>
        /// <param name="value">Desired value for the property.</param>
        /// <param name="propertyName">Name of the property used to notify listeners.  This
        /// value is optional and can be provided automatically when invoked from compilers that
        /// support CallerMemberName.</param>
        /// <returns>True if the value was changed, false if the existing value matched the
        /// desired value.</returns>
        protected bool Set<T>(ref T storage, T value, [CallerMemberName] String propertyName = null)
        {
            if (object.Equals(storage, value)) return false;
    
    		OnValidatePropertyChanging(storage, value, propertyName);
    		storage = value;
    		OnChanged(propertyName);
            return true;
        }

        #endregion

        #region Primitive Properties
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid MunitionGUID
        {
            get { return _munitionGUID; }
            set
    		{ 
    			Set(ref _munitionGUID, value);
    		}
    
        }
        private System.Guid _munitionGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Art
        {
            get { return _art; }
            set
    		{ 
    			Set(ref _art, value);
    		}
    
        }
        private string _art;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Name
        {
            get { return _name; }
            set
    		{ 
    			Set(ref _name, value);
    		}
    
        }
        private string _name;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int Preismodifikator
        {
            get { return _preismodifikator; }
            set
    		{ 
    			Set(ref _preismodifikator, value);
    		}
    
        }
        private int _preismodifikator;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Bemerkungen
        {
            get { return _bemerkungen; }
            set
    		{ 
    			Set(ref _bemerkungen, value);
    		}
    
        }
        private string _bemerkungen;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Literatur
        {
            get { return _literatur; }
            set
    		{ 
    			Set(ref _literatur, value);
    		}
    
        }
        private string _literatur;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual int Probe
        {
            get { return _probe; }
            set
    		{ 
    			Set(ref _probe, value);
    		}
    
        }
        private int _probe;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Spitze
        {
            get { return _spitze; }
            set
    		{ 
    			Set(ref _spitze, value);
    		}
    
        }
        private string _spitze;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual bool Härtbar
        {
            get { return _härtbar; }
            set
    		{ 
    			Set(ref _härtbar, value);
    		}
    
        }
        private bool _härtbar;

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual ICollection<Held_Munition> Held_Munition
        {
            get
            {
                if (_held_Munition == null)
                {
                    var newCollection = new FixupCollection<Held_Munition>();
                    newCollection.CollectionChanged += FixupHeld_Munition;
                    _held_Munition = newCollection;
                }
                return _held_Munition;
            }
            set
            {
                if (!ReferenceEquals(_held_Munition, value))
                {
                    var previousValue = _held_Munition as FixupCollection<Held_Munition>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupHeld_Munition;
                    }
                    _held_Munition = value;
                    var newValue = value as FixupCollection<Held_Munition>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupHeld_Munition;
                    }
                }
            }
        }
        private ICollection<Held_Munition> _held_Munition;
    
    	[DataMember]
        public virtual ICollection<Munition_Setting> Munition_Setting
        {
            get
            {
                if (_munition_Setting == null)
                {
                    var newCollection = new FixupCollection<Munition_Setting>();
                    newCollection.CollectionChanged += FixupMunition_Setting;
                    _munition_Setting = newCollection;
                }
                return _munition_Setting;
            }
            set
            {
                if (!ReferenceEquals(_munition_Setting, value))
                {
                    var previousValue = _munition_Setting as FixupCollection<Munition_Setting>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMunition_Setting;
                    }
                    _munition_Setting = value;
                    var newValue = value as FixupCollection<Munition_Setting>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMunition_Setting;
                    }
                }
            }
        }
        private ICollection<Munition_Setting> _munition_Setting;

        #endregion

        #region Association Fixup
    
        private void FixupHeld_Munition(object sender, NotifyCollectionChangedEventArgs e)
        {
    		OnChanged("Held_Munition");
            if (e.NewItems != null)
            {
                foreach (Held_Munition item in e.NewItems)
                {
                    item.Munition = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Held_Munition item in e.OldItems)
                {
                    if (ReferenceEquals(item.Munition, this))
                    {
                        item.Munition = null;
                    }
                }
            }
        }
    
        private void FixupMunition_Setting(object sender, NotifyCollectionChangedEventArgs e)
        {
    		OnChanged("Munition_Setting");
            if (e.NewItems != null)
            {
                foreach (Munition_Setting item in e.NewItems)
                {
                    item.Munition = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Munition_Setting item in e.OldItems)
                {
                    if (ReferenceEquals(item.Munition, this))
                    {
                        item.Munition = null;
                    }
                }
            }
        }

        #endregion

    }
}
