//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace MeisterGeister.Model
{
    [DataContract(IsReference=true)]
    public partial class Pflanze_Ernte : INotifyPropertyChanged
    {
        #region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    	
    	/// <summary>
        /// Notifies listeners that a property value has changed.
        /// </summary>
        /// <param name="propertyName">Name of the property used to notify listeners.  This
        /// value is optional and can be provided automatically when invoked from compilers
        /// that support <see cref="CallerMemberNameAttribute"/>.</param>
        protected void OnChanged([CallerMemberName] string propertyName = null)
        {
            var eventHandler = this.PropertyChanged;
            if (eventHandler != null)
            {
                eventHandler(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        #endregion

        #region ValidatePropertyChanging
    	protected event Extensions.ValidatePropertyChangingEventHandler ValidatePropertyChanging;
    
    	protected void OnValidatePropertyChanging(object currentValue, object newValue, [CallerMemberName] string propertyName = null)
    	{
    		if(ValidatePropertyChanging != null)
    		{
    			ValidatePropertyChanging(this, propertyName, currentValue, newValue);
    		}
    	}

        #endregion

        #region Set
    	/// <summary>
        /// Checks if a property already matches a desired value.  Sets the property and
        /// notifies listeners only when necessary.
        /// </summary>
        /// <typeparam name="T">Type of the property.</typeparam>
        /// <param name="storage">Reference to a property with both getter and setter.</param>
        /// <param name="value">Desired value for the property.</param>
        /// <param name="propertyName">Name of the property used to notify listeners.  This
        /// value is optional and can be provided automatically when invoked from compilers that
        /// support CallerMemberName.</param>
        /// <returns>True if the value was changed, false if the existing value matched the
        /// desired value.</returns>
        protected bool Set<T>(ref T storage, T value, [CallerMemberName] String propertyName = null)
        {
            if (object.Equals(storage, value)) return false;
    
    		OnValidatePropertyChanging(storage, value, propertyName);
    		storage = value;
    		OnChanged(propertyName);
            return true;
        }

        #endregion

        #region Primitive Properties
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid ID
        {
            get { return _iD; }
            set
    		{ 
    			Set(ref _iD, value);
    		}
    
        }
        private System.Guid _iD;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid PflanzeGUID
        {
            get { return _pflanzeGUID; }
            set
            {
                if (_pflanzeGUID != value)
                {
                    if (Pflanze != null && Pflanze.PflanzeGUID != value)
                    {
                        Pflanze = null;
                    }
                    _pflanzeGUID = value;
                }
            }
    
        }
        private System.Guid _pflanzeGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual short Von
        {
            get { return _von; }
            set
    		{ 
    			Set(ref _von, value);
    		}
    
        }
        private short _von;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual short Bis
        {
            get { return _bis; }
            set
    		{ 
    			Set(ref _bis, value);
    		}
    
        }
        private short _bis;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Grundmenge
        {
            get { return _grundmenge; }
            set
    		{ 
    			Set(ref _grundmenge, value);
    		}
    
        }
        private string _grundmenge;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Pflanzenteil
        {
            get { return _pflanzenteil; }
            set
    		{ 
    			Set(ref _pflanzenteil, value);
    		}
    
        }
        private string _pflanzenteil;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Haltbarkeit
        {
            get { return _haltbarkeit; }
            set
    		{ 
    			Set(ref _haltbarkeit, value);
    		}
    
        }
        private string _haltbarkeit;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string HaltbarkeitEinheit
        {
            get { return _haltbarkeitEinheit; }
            set
    		{ 
    			Set(ref _haltbarkeitEinheit, value);
    		}
    
        }
        private string _haltbarkeitEinheit;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual Nullable<int> Gewicht
        {
            get { return _gewicht; }
            set
    		{ 
    			Set(ref _gewicht, value);
    		}
    
        }
        private Nullable<int> _gewicht;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Bemerkung
        {
            get { return _bemerkung; }
            set
    		{ 
    			Set(ref _bemerkung, value);
    		}
    
        }
        private string _bemerkung;

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual Pflanze Pflanze
        {
            get { return _pflanze; }
            set
            {
                if (!ReferenceEquals(_pflanze, value))
                {
                    var previousValue = _pflanze;
                    _pflanze = value;
                    FixupPflanze(previousValue);
                }
            }
        }
        private Pflanze _pflanze;

        #endregion

        #region Association Fixup
    
        private void FixupPflanze(Pflanze previousValue)
        {
    		OnChanged("Pflanze");
            if (previousValue != null && previousValue.Pflanze_Ernte.Contains(this))
            {
                previousValue.Pflanze_Ernte.Remove(this);
            }
    
            if (Pflanze != null)
            {
                if (!Pflanze.Pflanze_Ernte.Contains(this))
                {
                    Pflanze.Pflanze_Ernte.Add(this);
                }
                if (PflanzeGUID != Pflanze.PflanzeGUID)
                {
                    PflanzeGUID = Pflanze.PflanzeGUID;
                }
            }
        }

        #endregion

    }
}
