//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel;

namespace MeisterGeister.Model
{
    [DataContract(IsReference=true)]
    public partial class Sonderfertigkeit_Setting : INotifyPropertyChanged
    {
        #region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    	
    	public void OnChanged(String info)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(info));
            }
        }

        #endregion

        #region Primitive Properties
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid SonderfertigkeitGUID
        {
            get { return _sonderfertigkeitGUID; }
            set
            {
                if (_sonderfertigkeitGUID != value)
                {
                    if (Sonderfertigkeit != null && Sonderfertigkeit.SonderfertigkeitGUID != value)
                    {
                        Sonderfertigkeit = null;
                    }
                    _sonderfertigkeitGUID = value;
                }
            }
    
        }
        private System.Guid _sonderfertigkeitGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid SettingGUID
        {
            get { return _settingGUID; }
            set
            {
                if (_settingGUID != value)
                {
                    if (Setting != null && Setting.SettingGUID != value)
                    {
                        Setting = null;
                    }
                    _settingGUID = value;
                }
            }
    
        }
        private System.Guid _settingGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Verbreitung
        {
            get { return _verbreitung; }
            set
    		{ 
    			_verbreitung = value;
    			OnChanged("Verbreitung");
    		}
    
        }
        private string _verbreitung;

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual Setting Setting
        {
            get { return _setting; }
            set
            {
                if (!ReferenceEquals(_setting, value))
                {
                    var previousValue = _setting;
                    _setting = value;
                    FixupSetting(previousValue);
                }
            }
        }
        private Setting _setting;
    
    	[DataMember]
        public virtual Sonderfertigkeit Sonderfertigkeit
        {
            get { return _sonderfertigkeit; }
            set
            {
                if (!ReferenceEquals(_sonderfertigkeit, value))
                {
                    var previousValue = _sonderfertigkeit;
                    _sonderfertigkeit = value;
                    FixupSonderfertigkeit(previousValue);
                }
            }
        }
        private Sonderfertigkeit _sonderfertigkeit;

        #endregion

        #region Association Fixup
    
        private void FixupSetting(Setting previousValue)
        {
    		OnChanged("Setting");
            if (previousValue != null && previousValue.Sonderfertigkeit_Setting.Contains(this))
            {
                previousValue.Sonderfertigkeit_Setting.Remove(this);
            }
    
            if (Setting != null)
            {
                if (!Setting.Sonderfertigkeit_Setting.Contains(this))
                {
                    Setting.Sonderfertigkeit_Setting.Add(this);
                }
                if (SettingGUID != Setting.SettingGUID)
                {
                    SettingGUID = Setting.SettingGUID;
                }
            }
        }
    
        private void FixupSonderfertigkeit(Sonderfertigkeit previousValue)
        {
    		OnChanged("Sonderfertigkeit");
            if (previousValue != null && previousValue.Sonderfertigkeit_Setting.Contains(this))
            {
                previousValue.Sonderfertigkeit_Setting.Remove(this);
            }
    
            if (Sonderfertigkeit != null)
            {
                if (!Sonderfertigkeit.Sonderfertigkeit_Setting.Contains(this))
                {
                    Sonderfertigkeit.Sonderfertigkeit_Setting.Add(this);
                }
                if (SonderfertigkeitGUID != Sonderfertigkeit.SonderfertigkeitGUID)
                {
                    SonderfertigkeitGUID = Sonderfertigkeit.SonderfertigkeitGUID;
                }
            }
        }

        #endregion

    }
}
