//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel;

namespace MeisterGeister.Model
{
    [DataContract(IsReference=true)]
    public partial class Zauberzeichen_Setting : INotifyPropertyChanged
    {
        #region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    	
    	public void OnChanged(String info)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(info));
            }
        }

        #endregion

        #region ValidatePropertyChanging
    	protected event Extensions.ValidatePropertyChangingEventHandler ValidatePropertyChanging;
    
    	protected void OnValidatePropertyChanging(String propertyName, object currentValue, object newValue)
    	{
    		if(ValidatePropertyChanging != null)
    		{
    			ValidatePropertyChanging(this, propertyName, currentValue, newValue);
    		}
    	}

        #endregion

        #region Primitive Properties
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid ZauberzeichenGUID
        {
            get { return _zauberzeichenGUID; }
            set
            {
                if (_zauberzeichenGUID != value)
                {
                    if (Zauberzeichen != null && Zauberzeichen.ZauberzeichenGUID != value)
                    {
                        Zauberzeichen = null;
                    }
                    _zauberzeichenGUID = value;
                }
            }
    
        }
        private System.Guid _zauberzeichenGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual System.Guid SettingGUID
        {
            get { return _settingGUID; }
            set
            {
                if (_settingGUID != value)
                {
                    if (Setting != null && Setting.SettingGUID != value)
                    {
                        Setting = null;
                    }
                    _settingGUID = value;
                }
            }
    
        }
        private System.Guid _settingGUID;
    	///<summary>Database persistent property</summary>
    	[DataMember]
        public virtual string Verbreitung
        {
            get { return _verbreitung; }
            set
    		{ 
    			OnValidatePropertyChanging("Verbreitung",_verbreitung, value);
    			_verbreitung = value;
    			OnChanged("Verbreitung");
    		}
    
        }
        private string _verbreitung;

        #endregion

        #region Navigation Properties
    
    	[DataMember]
        public virtual Setting Setting
        {
            get { return _setting; }
            set
            {
                if (!ReferenceEquals(_setting, value))
                {
                    var previousValue = _setting;
                    _setting = value;
                    FixupSetting(previousValue);
                }
            }
        }
        private Setting _setting;
    
    	[DataMember]
        public virtual Zauberzeichen Zauberzeichen
        {
            get { return _zauberzeichen; }
            set
            {
                if (!ReferenceEquals(_zauberzeichen, value))
                {
                    var previousValue = _zauberzeichen;
                    _zauberzeichen = value;
                    FixupZauberzeichen(previousValue);
                }
            }
        }
        private Zauberzeichen _zauberzeichen;

        #endregion

        #region Association Fixup
    
        private void FixupSetting(Setting previousValue)
        {
    		OnChanged("Setting");
            if (previousValue != null && previousValue.Zauberzeichen_Setting.Contains(this))
            {
                previousValue.Zauberzeichen_Setting.Remove(this);
            }
    
            if (Setting != null)
            {
                if (!Setting.Zauberzeichen_Setting.Contains(this))
                {
                    Setting.Zauberzeichen_Setting.Add(this);
                }
                if (SettingGUID != Setting.SettingGUID)
                {
                    SettingGUID = Setting.SettingGUID;
                }
            }
        }
    
        private void FixupZauberzeichen(Zauberzeichen previousValue)
        {
    		OnChanged("Zauberzeichen");
            if (previousValue != null && previousValue.Zauberzeichen_Setting.Contains(this))
            {
                previousValue.Zauberzeichen_Setting.Remove(this);
            }
    
            if (Zauberzeichen != null)
            {
                if (!Zauberzeichen.Zauberzeichen_Setting.Contains(this))
                {
                    Zauberzeichen.Zauberzeichen_Setting.Add(this);
                }
                if (ZauberzeichenGUID != Zauberzeichen.ZauberzeichenGUID)
                {
                    ZauberzeichenGUID = Zauberzeichen.ZauberzeichenGUID;
                }
            }
        }

        #endregion

    }
}
