-- Update Waffen
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 93' WHERE WaffeID = 1;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 38' WHERE WaffeID = 2;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 32' WHERE WaffeID = 3;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 25' WHERE WaffeID = 4;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 92' WHERE WaffeID = 5;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 83' WHERE WaffeID = 6;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 74' WHERE WaffeID = 7;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 75' WHERE WaffeID = 8;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 67' WHERE WaffeID = 9;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 25' WHERE WaffeID = 10;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 11' WHERE WaffeID = 11;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 11' WHERE WaffeID = 12;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 95' WHERE WaffeID = 13;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 72' WHERE WaffeID = 14;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 33' WHERE WaffeID = 15;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 26' WHERE WaffeID = 16;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 26' WHERE WaffeID = 17;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 92' WHERE WaffeID = 18;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 60' WHERE WaffeID = 19;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 11' WHERE WaffeID = 20;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 78, ERRATA 4' WHERE WaffeID = 21;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 86' WHERE WaffeID = 22;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 86' WHERE WaffeID = 23;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 18' WHERE WaffeID = 24;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 12' WHERE WaffeID = 25;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 78' WHERE WaffeID = 26;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 19' WHERE WaffeID = 27;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 94, ERRATA 5' WHERE WaffeID = 28;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 55' WHERE WaffeID = 29;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 54' WHERE WaffeID = 30;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 12' WHERE WaffeID = 31;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 17' WHERE WaffeID = 32;
UPDATE Waffe SET Literatur = N'Wege des Schwerts 125' WHERE WaffeID = 33;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal  87, ERRATA 4' WHERE WaffeID = 34;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 13' WHERE WaffeID = 35;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 61' WHERE WaffeID = 36;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 13' WHERE WaffeID = 37;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 33' WHERE WaffeID = 38;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 84, ERRATA 4' WHERE WaffeID = 39;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 93' WHERE WaffeID = 40;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 61' WHERE WaffeID = 41;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 33' WHERE WaffeID = 42;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 13' WHERE WaffeID = 43;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 34' WHERE WaffeID = 44;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 13' WHERE WaffeID = 45;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 19' WHERE WaffeID = 46;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 19' WHERE WaffeID = 47;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 90' WHERE WaffeID = 48;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 20' WHERE WaffeID = 49;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 20, 90, ERRATA 4' WHERE WaffeID = 50;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 62' WHERE WaffeID = 51;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 65' WHERE WaffeID = 52;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 65' WHERE WaffeID = 53;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 66' WHERE WaffeID = 54;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 79' WHERE WaffeID = 55;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 55' WHERE WaffeID = 56;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 54' WHERE WaffeID = 57;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 54' WHERE WaffeID = 58;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 14' WHERE WaffeID = 59;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 55' WHERE WaffeID = 60;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 80' WHERE WaffeID = 61;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 34' WHERE WaffeID = 62;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 34' WHERE WaffeID = 63;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 38' WHERE WaffeID = 64;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 27' WHERE WaffeID = 65;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 62' WHERE WaffeID = 66;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 66' WHERE WaffeID = 67;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 27' WHERE WaffeID = 68;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 88' WHERE WaffeID = 69;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 63' WHERE WaffeID = 70;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 56' WHERE WaffeID = 71;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 56' WHERE WaffeID = 72;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 56' WHERE WaffeID = 73;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 57' WHERE WaffeID = 74;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 56' WHERE WaffeID = 75;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 56, ERRATA 3' WHERE WaffeID = 76;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 68' WHERE WaffeID = 77;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 67' WHERE WaffeID = 78;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 14' WHERE WaffeID = 79;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 14' WHERE WaffeID = 80;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 67' WHERE WaffeID = 81;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 75' WHERE WaffeID = 82;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 27' WHERE WaffeID = 83;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 82' WHERE WaffeID = 84;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 35' WHERE WaffeID = 85;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 15' WHERE WaffeID = 86;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 28' WHERE WaffeID = 87;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 20' WHERE WaffeID = 88;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 28' WHERE WaffeID = 89;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 69' WHERE WaffeID = 90;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 76, ERRATA 4' WHERE WaffeID = 91;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 85' WHERE WaffeID = 92;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 97' WHERE WaffeID = 93;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 28' WHERE WaffeID = 94;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 35' WHERE WaffeID = 95;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 15' WHERE WaffeID = 96;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 36' WHERE WaffeID = 97;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 39, 57' WHERE WaffeID = 98;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 63' WHERE WaffeID = 99;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 63' WHERE WaffeID = 100;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 94, ERRATA 5' WHERE WaffeID = 101;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 57' WHERE WaffeID = 102;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 91, ERRATA 5' WHERE WaffeID = 103;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 58' WHERE WaffeID = 104;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 58' WHERE WaffeID = 105;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 39' WHERE WaffeID = 106;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 55' WHERE WaffeID = 107;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 30, ERRATA 2' WHERE WaffeID = 108;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 68' WHERE WaffeID = 109;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 58' WHERE WaffeID = 110;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 36' WHERE WaffeID = 111;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 69' WHERE WaffeID = 112;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 16' WHERE WaffeID = 113;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 16' WHERE WaffeID = 114;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 84' WHERE WaffeID = 115;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 76' WHERE WaffeID = 116;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 59' WHERE WaffeID = 117;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 21, ERRATA 1' WHERE WaffeID = 118;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 16' WHERE WaffeID = 119;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 64' WHERE WaffeID = 120;
UPDATE Waffe SET Literatur = N'Wege des Schwerts 126' WHERE WaffeID = 121;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 22' WHERE WaffeID = 122;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 30' WHERE WaffeID = 123;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 30' WHERE WaffeID = 124;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 17' WHERE WaffeID = 125;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 36' WHERE WaffeID = 126;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 39' WHERE WaffeID = 127;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 31' WHERE WaffeID = 128;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 82' WHERE WaffeID = 129;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 69' WHERE WaffeID = 130;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 16' WHERE WaffeID = 131;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 59' WHERE WaffeID = 132;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 80' WHERE WaffeID = 133;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 37' WHERE WaffeID = 134;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 91, ERRATA 5' WHERE WaffeID = 135;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 77' WHERE WaffeID = 136;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 71' WHERE WaffeID = 137;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 77' WHERE WaffeID = 138;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 71' WHERE WaffeID = 139;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 23' WHERE WaffeID = 140;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 89' WHERE WaffeID = 141;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 37' WHERE WaffeID = 142;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 64' WHERE WaffeID = 143;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 89' WHERE WaffeID = 144;
UPDATE Waffe SET Literatur = N'Aventurisches Arsenal 89, ERRATA 4' WHERE WaffeID = 145;