-- Neue Zauber aus Stätten okkulter Macht
--Zauber: Ecliptifactus Schattenkraft (obsk.) [Mag]
--Zauber: Nuntiovolo Botenvogel (obsk.) [Mag]
--Zauber: Opacitas Schattenleib [Mag]
--Zauber: Pantenebrum [Mag]
--Zauber: Schattenodem [Mag]
--Zauber: Umbraporta Schattentüre [Mag]