-- Sonderfertigkeiten WdA
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Alfenbannrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Bärenrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Entgifterrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Geisterbannrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Lebensrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Nebelrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Orkanstimmenrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Salzwasserrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Waberlohenrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Zukunftsrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Schutzkreis gegen Untote', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Auge des Mondes', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Fallensiegel', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Fixierungszeichen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Gezücht des Meisters', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Hypnotisches Zeichen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Siegel der Stille', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Siegel der zweiten Haut', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Sigille der Schatten', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Sigille des unsichtbaren Trägers', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Sigille des unsichtbaren Weges', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Verderben des Magiers', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Verständigungszeichen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Wimmelndes Zeichen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Wunschglyphe', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Zeichen des Handwerks', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Zeichen des Stillstands', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Zeichen des versperrten Blick', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Zeichen gegen Magie', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Kraftquellenspeisung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Magiewiderstand', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Potenzierung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Tarnung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Verkleinerung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Zielbeschränkung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Reaktivierungsgespür (Arkanoglyphen)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Reaktivierungsgespür (Rundenkunde)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Spontanzeichen (Arkanoglyphen)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Spontanzeichen (Rundenkunde)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Auxiliator', 0, 'Magisch');

-- Sonderfertigkeiten - Liturgien
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Achmad''ayan Ankhrellah Al''nurach Shaitanim', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Aller Welt Freund', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Allmacht der Lohe', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Alte Schuppen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Am Busden der Natur', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Anathema', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Angroschs Opfergabe', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Angroschs Zorn', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Anrufung der Erdkraft', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Anrufung der Winde', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Anrufung der Winde (III)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Anrufung der Winde (IV)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Anrufung der Winde (V)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Anrufung Nuiannas', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Arcanum Interdictum', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Argelions Bannende Hand', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Argelions Mantel', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Argelions Spiegel', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ascandears Hingabe', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Auge der wartenden Seelen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Auge des Händlers', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Auge des Mondes ', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Aura der Form', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Aura des Regenbogens', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Azilas Quellgesang', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Bann der Geisterkräfte', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Bannfluch des Heiligen Khalid', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Begehen der Heiligen Wasser', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Belemans Hochzeit', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Bindung der Schlange', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Bishdariels Angesicht', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Bishdariels Auge', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Bishdariels Auge (III)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Bishdariels Auge (IV)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Bishdariels Warnung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Blendstrahl aus Alveran', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Blick an den klaren Himmel', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Blick auf das Geisterwirken', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Blick der Weberin', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Blick durch Tairachs Augen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Blick für das Handwerk', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Blick in die Erinnerung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Blick in die Flammen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Bootssegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Borons süße Gnade', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Borons süße Gnade (V)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Buchprüfung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Cereborns Handreichung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Daradors Bann der Schatten', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Darados prüfender Blick', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Das schwarze Fell durch das Rote Blut', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Der Gänsemutter warmes Nest', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Des Herren Goldener Mittag', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Dorlens Verbrüderung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Dreifacher Saatsegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Dythlinds Wandeln im Feuer', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Efferdsegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ehrene Kraft - lodernder Zorn', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ehrenhafter Zweikampf', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Eidechsenhaut', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Eidsegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Eidsegen (II)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ein Bild für die Ewigkeit', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ein Freund in Zeiten der Not', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Elementwandlung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Entzug des Wissens', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Entzug von Nandus'' Gaben', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Erlösung des Tapams', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Erneuerung des Geborstenen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Erneuerung des Geborstenen (V)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Etilias Gnade', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Etilias Zeit der Meditaion', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ewiger Wächter', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ewiges Wissen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Exkommunikation', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Exkommunikation (IV)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Exkommunikation (V)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Exorzismus', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Exorzismus (IV)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Exorzismus (V)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Exorzismus (VI)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Feuersegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Feuertaufe', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Firuns Einsicht', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Flagge des Regenbogens', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Freundliche Aufnahme', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Frieden der Melodie', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Fünfte Lobpreisung des Frühlings', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Fürbitten des Heiligen Therbun', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Garfans Gleißende Schwingen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Gebieter der Lava', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Geburtssegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Geistermantel', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Geläutert sei Erz und Goldgestein', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Gemeinschaft der treuen Gefährten', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Gesang der Delphine', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Gesang der Wale', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Gesegneter Fang', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Geteiltes Leid', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Gift der Erkenntnis', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Gift der Erkenntnis (III)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Gilborns heilige Aura', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Gleichklang des Geistes', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Glückssegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Goldene Rüstung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Goldener Blick', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Gorfangs Fluch', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Göttliche Verständigung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Göttliche Verständigung (III)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Göttliche Verständigung (IV)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Göttliches Zeichen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Göttliches Zeichen (III)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Grabsegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Graues Siegel', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Grispelz'' Ackersegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Grispelz'' Fruchtbarkeit', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Große Seelenwaschung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Große Weihe des Heimsteins', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Großer Eidsegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Großer Giftbann', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Großer Reisesegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Großer Speisesegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Großer Weihesegen der Waffe', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Großes Tabus', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Gruß der Versunkenen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Händlersegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Handwerksegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Harmoniesegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Hashnabiths Flehen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Hauch Borons', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Hauch der Leidenschaft', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Hausfrieden', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Haut des Chamäleons', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Heilige Salbung der Peraine', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Heilige Schmiedeglut', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Heiliger Befehl', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Heiliger Lehenseid', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Heiliges Liebesspiel', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Heilung des Tapams', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Heilungssegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Herr über Feuer und Glut', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Hesindes Fingerzeig', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Hilfe in der Not', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Hoftag der Sprachen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Indoktination', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ingalfs Alchimie', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ingerimms Zorn verschone uns', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Initiation', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Innere Ruhe', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Jagdglück', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Jagdglück (IV)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Jagdglück (V)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Kälbchensegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Kamaluqs Fluch', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Kamaluqs unerbittlicher Speer', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Khabals makelloser Leib', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Khabals makelloser Leib (VI)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Khablas Jugend', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Khablas Jugend (IV)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Kirschblütensegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Kleine Liturgie des heiligen Nemekath', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Kleine Segnung des Heimsteins', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Kleiner Giftbann', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Kleiner Giftbann (III)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Kleines Tabu', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Konserkation', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Kräftigung der Schwachen und Versehrten', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Kräftigung der Schwachen und Versehrten (VI)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Kräutersegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Largorax'' Hammer rufen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Levthans Fesseln', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Licht des Herrn', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Licht des verborgenen Pfades', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Lohn der Unverzagten', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Lug und Trug', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Mannschaftssegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Marbos Geisterblick', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Marbos Geleit', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Märtyrersegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Meisterstück', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Mondsilberzunge', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Nandus'' Schriftkenntnis', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Nemekaths Bannfluch', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Nemekaths Geisterblick', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Nemekaths Zwiesprache', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Neun Streiche in Einem', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Nimmermüde Wanderschaft', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Noionas Zuspruch', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Obarans Bannstrahl', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Objektsegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Objektsegen (II)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Objektsegen (IV)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Objektweihe', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Objektweihe (III)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Objektweihe (IV)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Objektweihe (V)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Objektweihe (VI)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ordination', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Parinors Vermächtnis', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Peraines Pflanzengespür', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Phexens Augenzwinkern', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Phexens Elsterflug', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Phexens Kunstverstand', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Phexens Meisterschlüssel', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Phexens Nebelleib', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Phexens Schatten', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Phexens Sternenwurf', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Phexens wunderbare Verständigung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Praios'' Magiebann', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Praios'' Mahnung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Prophezeiung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Purgation', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Purgation (V)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Quellsegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Rahjalinas Kuss', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Rahjalinas Weinranke', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Rahjas Erquickung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Rahjas Fest der Freude', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Rahjas Freiheit', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Rahjas geheiligter Wein', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Rahjas heitere Gelassenheit', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Rahjas Rauschsegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Rahjas Schoß', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Rahjas Sinnlichkeit', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Reichung des Amethyst', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Reichung des Amethyst (II)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Reichung des Amethyst (III)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Reichung des Amethyst (V)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Reisesegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Reisesegen (III)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Rondras Hochzeit', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Rondras wundersame Rüstung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ruf der Gefährten', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ruf der Gefährten (IV)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ruf in Borons Arme', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ruf zur Ruhe', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Salbung der heiligen Noiona', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Sankt Gilborns Bannfluch', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Schattenlarve', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Schiffssegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Schlaf des Gesegneten', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Schlangenstab', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Schneesturm/ Eissturm', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Schrifttum ferner Lande', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Schutz des Gelges', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Schutzsegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Schutzsegen (II)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Schutzsegen (III)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Schwitzhütte', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Seelenprüfung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Seelenprüfung (IV)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Seelenprüfung (V)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Segen der Gabetaj', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Segen der Heiligen Ardare', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Segen der heiligen Noiona', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Segen der heiligen Noiona (IV)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Segen der heiligen Theria', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Segen der heiligen Velvenya', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Segen des Heiligen Badilak', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Segen des Heiligen Hluthar', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Segen des Plättlings', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Segenreiches Wasser', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Segnung der Schlacht', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Segnung der Stählernen Stirn', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Segnung des Heimes', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Sichere Wanderung im Schnee', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Sichere Wanderung im Schnee (III)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Sicherer Weg durch Fels', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Sicht auf Madas Welt', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Siegel Borons', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Simias Kelch', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Sippenfluch', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Speisesegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Speisung der Bedürftigen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Speisung der hungernden Seelen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Speisung der hungernden Seelen (IV)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Sprechende Symbole', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Sterne funkeln immerfort', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Sternenglanz', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Sternenspur', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Sternenstaub', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Sulvas Gnade', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Swafnirs Fluke', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Swafnirs Ruhelied', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Tabu', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Tairachs Fluch', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Thalionmels Schlachtensang', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Therbuns Erkenntnis', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Tierempathie', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Tierempathie (III)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Tiergestalt', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Tranksegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Traviabund', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Travianians Segen der Schwelle', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Travias Gebet der sicheren Zuflucht', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Travias Gebet der sicheren Zuflucht (VI)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Travias Gebet der verborgenen Halle', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Trophäe erhalten', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Tsas Ewige Jugend', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Tsas heiliges Lebensgeschenk', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Tsas Lebensschutz', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Tsas segenreicher Neuanfang', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Tsas wunderbare Erneuerung', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Tsas wundersame Fruchtbarkeit', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Über die Wolken', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Über die Wolken (VI)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Ucuris Geleit', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Unterpfand des heiligen Rhys', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Unverstellter Blick', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Urischars Ordnender Blick', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Vaes Tränen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Verborgen wie der Neumond', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Versiegeltes Wissen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Vertrauter der Flamme', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Vertrauter des Felsesens', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Vertreibung des Dunkelsinns', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Vertreibung des Dunkelsinns (V)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Visionssuche', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Waliburias Wehr', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Wandeln in Hesindes Hain', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Weg des Fuchses', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Weihe der ewigen Flamme', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Weihe der letzten Ruhestatt', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Weihgesang der Heiligen Elida von Salza', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Weisheitssegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Weisung des Himmels', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Wille zur Wahrheit', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Winterschlaf', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Wort der Wahrheit', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Wunderbarer Geschlechterwandel', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Wundersame Blütenbracht', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Wundsegen', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Wundsegen (III)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Wundsegen (IV)', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Zerschmetternder Bannstrahl', 0, 'Klerikal - Liturgie');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgie: Zuflucht finden', 0, 'Klerikal - Liturgie');