-- Erweiterung: Held-Tabelle
ALTER TABLE Held ADD AU_Mod int DEFAULT 0, AU_Aktuell int, AE_Mod int DEFAULT 0, AE_Aktuell int, KE_Mod int DEFAULT 0, KE_Aktuell int, MR_Mod int DEFAULT 0, Kampfwerte nvarchar(500) DEFAULT 'Waffe: DK N AT ? PA ? TP 1W6+?', Wunden int DEFAULT 0;
ALTER TABLE Held_Sonderfertigkeit ALTER COLUMN Wert nvarchar(300);

-- Sonderfertigkeiten
UPDATE Sonderfertigkeit SET Name = 'Meisterliches Entwaffnen' WHERE SonderfertigkeitID = 45;
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Objektritual: Apport', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Astrale Meditation', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Aura verhüllen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Aurapanzer', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Objektritual: Bannschwert', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Bann- und Schutzkreis gegen Geisterwesen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Bann- und Schutzkreis gegen niedere Dämonen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Bann- und Schutzkreis gegen Elementare', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Bann- und Schutzkreis gegen gehörnte Dämonen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Bannkreis gegen Traumgänger', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Schutzkreis gegen Ungeziefer', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Schutzkreis gegen Reptilien', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Bannkreis gegen Chimären', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Leuchtendes Zeichen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Singendes Zeichen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Siegel der Seelenruhe', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Hermetisches Siegel', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Glyphe der Elementaren Attraktion', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Ungesehenes Zeichen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Glyphe der Elementaren Bannung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Zähne des Feuers', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Zeichen der Zauberschmiede', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Markierung des Todes', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Fanal der Herrschaft', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Glyphe des verfluchten Goldes', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Auge der Ewigen Wacht', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Auge des Basilisken', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Satinavs Siegel', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen: Schutzsiegel', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Blutmagie', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Chimärenmeister', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Dämonenbindung I', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Dämonenbindung II', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidenrache', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Dolchritual: Weihe', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Dolchritual: Gespür', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Dolchritual: Licht', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Dolchritual: Bann', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Dolchritual: Leib', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Dolchritual: Schutz', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Dolchritual: Weg', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Dolchritual: Ernte', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Dolchritual: Lebenskraft', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Dolchritual: Opferdolch', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Dolchritual: Schneide', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Dolchritual: Weisung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Herrschaftsritual: Wachs der Herrschaft', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Herrschaftsritual: Miniatur der Herrschaft', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Herrschaftsritual: Kristall der Herrschaft', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Herrschaftsritual: Amulett der Herrschaft', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Druidisches Herrschaftsritual: Wurzel des Blutes', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Eiserner Wille I', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Eiserner Wille II', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Elementarharmonisierte Aura (Eis/Humus)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Elementarharmonisierte Aura (Fels/Luft)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Elementarharmonisierte Aura (Feuer/Wasser)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Elfenlied: Sorgenlied', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Elfenlied: Zaubermelodie', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Elfenlied: Friedenslied', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Elfenlied: Windgeflüster', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Elfenlied: Lied der Lieder', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Elfenlied: Freundschaftslied', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Elfenlied: Erinnerungsmelodie', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Elfenlied: Melodie der Kunstfertigkeit', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Elfenlied: Lied des Trostes', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Elfenlied: Lied der Reinheit', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Exorzist', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Fernzauberei', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Form der Formlosigkeit', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Geber der Gestalt', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Gedankenschutz', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Gefäß der Sterne', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Geodenritual: Gestalt aus Rauch', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Geodenritual: Trank des ungehinderten Weges', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Golembauer', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Große Meditation', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Ängste mehren', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Beiß auf Granit', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Beute', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Hagelschlag', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Hexenschuss', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Kornfäule', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Krötenkuss', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Mit Blindheit schlagen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Pech an den Hals', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Pestilenz', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Schlaf rauben', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Todesfluch', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Unfruchtbarkeit', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Viehverstümmelung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Warzen sprießen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hexenfluch: Zunge lähmen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Höhere Dämonenbindung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Hypervehemenz', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Invocatio Integra', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Keulenritual: Bann der Keule', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Keulenritual: Geist der Keule', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Keulenritual: Gespür der Keule', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Keulenritual: Härte der Keule', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Keulenritual: Hilfe der Keule', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Keulenritual: Kraft der Keule', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Keulenritual: Nähe zur Natur', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Keulenritual: Opferkeule', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Keulenritual: Weihe der Keule', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Keulenritual: Zauber der Keule', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Konzentrationsstärke', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kraftkontrolle', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kraftlinienmagie I', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kraftlinienmagie II', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kraftspeicher', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kristallomantisches Ritual: Kristallbindung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kristallomantisches Ritual: Kristallformung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kristallomantisches Ritual: Thesiskristall', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kristallomantisches Ritual: Madakristall', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kristallomantisches Ritual: Matrixkristall', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kristallomantisches Ritual: Kristallkraft Bündeln', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kugelzauber: Bindung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kugelzauber: Brennglas und Prisma', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kugelzauber: Schutz gegen Untote', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kugelzauber: Warnendes Leuchten', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kugelzauber: Kugel des Hellsehers', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kugelzauber: Kugel des Illusionisten', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kugelzauber: Orbitarium', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kugelzauber: Bilderspiel', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kugelzauber: Fernbild', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kugelzauber: Bildergalerie', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kugelzauber: H''Szints Auge', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kugelzauber: Farben des Geistes', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kugelzauber: Wachendes Auge', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Lockeres Zaubern', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Matrixgeber', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Matrixkontrolle', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Matrixregeneration I', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Matrixregeneration II', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Matrixverständnis', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Meisterliche Regeneration', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Meisterliche Zauberkontrolle I', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Meisterliche Zauberkontrolle II', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Antimagie)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Beschwörung)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Dämonisch (Agrimoth))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Dämonisch (Amazeroth))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Dämonisch (Asfaloth))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Dämonisch (Belhalhar))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Dämonisch (Belkelel))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Dämonisch (Belshirash))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Dämonisch (Belzhorash))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Dämonisch (Blakharaz))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Dämonisch (Charyptoroth))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Dämonisch (gesamt))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Dämonisch (Lolgramoth))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Dämonisch (Tasfarelel))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Dämonisch (Thargunitoth))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Eigenschaften)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Einfluss)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Elementar (Eis))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Elementar (Erz))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Elementar (Feuer))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Elementar (gesamt))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Elementar (Humus))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Elementar (Luft))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Elementar (Wasser))', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Form)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Geisterwesen)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Heilung)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Hellsicht)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Herbeirufung)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Herrschaft)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Illusion)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Kraft)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Limbus)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Metamagie)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Objekt)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Schaden)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Telekinese)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Temporal)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Umwelt)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Merkmalskenntnis (Verständigung)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Nekromant', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Odûn-Gabe: Hauch des Odûn', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Odûn-Gabe: Haut des Odûn', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Odûn-Gabe: Blut des Odûn', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Odûn-Gabe: Ruf des Odûn', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Odûn-Gabe: Seele des Odûn', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ottagaldr', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Regeneration I', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Regeneration II', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Repräsentation (Achaz-Kristallomantisch)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Repräsentation (Borbaradianisch)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Repräsentation (Druidisch)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Repräsentation (Elfisch)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Repräsentation (Geodisch)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Repräsentation (Gildenmagisch)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Repräsentation (Hexisch)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Repräsentation (Scharlatanisch)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Repräsentation (Schelmisch)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Gildenmagie)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Kristallomantie)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Scharlatanerie)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Alchimie)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Hexenmagie)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Geoden)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Druiden)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Derwische)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Durro-Dûn)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Kristallomantie)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Zaubertänze)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Zibilja)', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runenkunde', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Rauschrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Friedensrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Ottarune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Finsterrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Wogensturmrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Felsenrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Schicksalsrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Pfeilrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Waffenrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Drachenrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Furchtrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Runen: Blutrune', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Salasandra', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schalenzauber: Weihe der Schale', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schalenzauber: Allegorische Analyse', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schalenzauber: Chymische Hochzeit', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schalenzauber: Mandricons Bindung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schalenzauber: Feuer und Eis', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schalenzauber: Transmutation der Elemente', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schlangenring-Zauber: Weihe der Schlange', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schlangenring-Zauber: Magnetismus', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schlangenring-Zauber: Wasserbann', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schlangenring-Zauber: Macht über den Regen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schlangenring-Zauber: Seelenfeuer', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schlangenring-Zauber: Herr der Flammen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schlangenring-Zauber: Macht des Lebens', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schlangenring-Zauber: Kräfte der Natur', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schlangenring-Zauber: Wirbelnder Luftschild', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schlangenring-Zauber: Launen des Windes', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schlangenring-Zauber: Weg durch Sumus Leib', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schuppenbeutel: Bindung des Schuppenbeutels', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Trank des ungehinderten Weges', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Die Gestalt aus Rauch', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schuppenbeutel: Suchende Finger', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schuppenbeutel: Ewige Wegzehrung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Semipermanenz I', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Semipermanenz II', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Signaturkenntnis', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Simultanzaubern', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Stabzauber: Bindung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Stabzauber: Ewige Flamme', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Stabzauber: Seil des Adepten', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Stabzauber: Stabverlängerung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Stabzauber: Hammer des Magus', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Stabzauber: Kraftfokus', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Stabzauber: Modifikationsfokus', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Stabzauber: Zauberspeicher', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Stabzauber: Merkmalsfokus', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Stabzauber: Flammenschwert', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Stabzauber: Schuppenhaut', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Stapeleffekt', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Tanz der Mada', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Tierischer Begleiter', 1, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Traumgänger', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Trommelzauber: Ruf des Krieges', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Trommelzauber: Sturm der Wüste', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Trommelzauber: Schutz Rastullahs', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Trommelzauber: Rastullahs Güte', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Trommelzauber: Zorn des Gottgefälligen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Verbotene Pforten', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Vertrautenbindung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Vielfache Ladungen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauber bereithalten', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauber unterbrechen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberkontrolle', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberroutine', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberspezialisierung', 1, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Firuns Jagd', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Madayana', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Rahjas Begehren', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Selinata', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Tanz der Bilder', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Tanz der Erlösung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Tanz der Ermutigung', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Tanz der Gemeinschaft', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Tanz der Freude', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Tanz der Liebe', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Tanz der Unantastbarkeit', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Tanz der Wahrheit', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Tanz der Weisheit', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Tanz des Ungehorsams', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zaubertanz: Tanz ohne Ende', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zauberzeichen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zibilja-Ritual: Schwarmseele', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zibilja-Ritual: Mackestopp', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zibilja-Ritual: Traumseherin', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zibilja-Ritual: Weisheit der Schrift', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zibilja-Ritual: Siegel der Ewigen Ruhe', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zibilja-Ritual: Unsichtbare Chronik', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zibilja-Ritual: Ruf des Bienenstocks', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zibilja-Ritual: Winterlager', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zibilja-Ritual: Bienenschwarm', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zibilja-Ritual: Wachshaut', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zibilja-Ritual: Bienenkönigin', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zibilja-Ritual: Bienenfleiß', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zibilja-Ritual: Bienentanz', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Zibilja-Ritual: Traumwissen', 0, 'Magisch');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Akoluth', 1, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Aura der Heiligkeit', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Karmalqueste', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kontakt zum Großen Geist', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Angrosch)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Aves)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Boron)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Efferd)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Firun)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Hesinde)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Ifirn)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Ingerimm)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Kor)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Namenloser)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Nandus)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Peraine)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Phex)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Praios)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Rahja)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Rondra)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Swafnir)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Travia)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Tsa)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (H''Szint)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Liturgiekenntnis (Zsahh)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Waldmenschen-Schamane)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Nivesen-Schamane)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Ferkina-Schamane)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Gjalsker-Schamane)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Trollzacker-Schamane)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Ork-Schamane)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Goblin-Schamanin)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Ritualkenntnis (Achaz-Schamane)', 0, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Spätweihe Alveranische Gottheit', 1, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Spätweihe Nichtalveranische Gottheit', 1, 'Klerikal');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Spätweihe Namenloser', 0, 'Klerikal');

-- Einstellungen
CREATE TABLE Einstellungen (Name nvarchar(100) PRIMARY KEY, WertBool bit, WertString nvarchar(300), WertInt int);
INSERT INTO Einstellungen (Name, WertBool) VALUES ('WuerfelSoundAbspielen', 1);

-- Vor-/Nachteile
UPDATE VorNachteil SET Name = 'Begabung für Merkmal (Herbeirufung)' WHERE VorNachteilID = 49;
DELETE FROM VorNachteil WHERE VorNachteilID = 90;
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Geweiht [zwölfgöttliche Kirche]', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Geweiht [H''Ranga]', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Geweiht [Angrosch]', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Geweiht [Gravesh]', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Geweiht [nicht-alveranische Gottheit]', 1, 1);
UPDATE VorNachteil SET Name = 'Tierempathie (alle)', HatWert = 0 WHERE VorNachteilID = 143;
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Tierempathie (speziell)', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Herrschsucht', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Landangst', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Charyptophilie', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Ruhelosigkeit', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Treulosigkeit', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Nekromantismus', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Schlaflosigkeit', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Jagdfieber', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Nagrachwahn', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Schöpferwahn', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Morbidität', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Agrimothwahn', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Konstruktionswahn', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Grausamkeit', 1, 1, 'int');
DELETE FROM VorNachteil WHERE VorNachteilID = 224;
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Miserable Eigenschaft (CH)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Miserable Eigenschaft (FF)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Miserable Eigenschaft (GE)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Miserable Eigenschaft (IN)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Miserable Eigenschaft (KK)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Miserable Eigenschaft (KL)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Miserable Eigenschaft (KO)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Miserable Eigenschaft (MU)', 1, 0);
UPDATE VorNachteil SET Name = 'Verschwendungssucht' WHERE VorNachteilID = 309;
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Viertelzauberer (unbewusst)', 1, 0);

-- Talente
INSERT INTO Talentgruppe (Gruppenname, Kurzname) VALUES ('Ritualkenntnis', 'Ritualkenntnis');
INSERT INTO Talentgruppe (Gruppenname, Kurzname) VALUES ('Liturgiekenntnis', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Talenttyp, Quelle, WikiLink) VALUES ('Ritualkenntnis (Gildenmagie)', 10, 'Spezial', 'WdZ 105ff.', 'Ritualkenntnis (Tradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Talenttyp, Quelle, WikiLink) VALUES ('Ritualkenntnis (Kristallomantie)', 10, 'Spezial', 'WdZ 105ff.', 'Ritualkenntnis (Tradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Talenttyp, Quelle, WikiLink) VALUES ('Ritualkenntnis (Scharlatanerie)', 10, 'Spezial', 'WdZ 105ff.', 'Ritualkenntnis (Tradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Talenttyp, Quelle, WikiLink) VALUES ('Ritualkenntnis (Alchimie)', 10, 'Spezial', 'WdZ 105ff.', 'Ritualkenntnis (Tradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Talenttyp, Quelle, WikiLink) VALUES ('Ritualkenntnis (Hexenmagie)', 10, 'Spezial', 'WdZ 105ff.', 'Ritualkenntnis (Tradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Talenttyp, Quelle, WikiLink) VALUES ('Ritualkenntnis (Vertrautenmagie)', 10, 'Spezial', 'WdZ 122', 'Ritualkenntnis (Tradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Talenttyp, Quelle, WikiLink) VALUES ('Ritualkenntnis (Geoden)', 10, 'Spezial', 'WdZ 105ff.', 'Ritualkenntnis (Tradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Talenttyp, Quelle, WikiLink) VALUES ('Ritualkenntnis (Druiden)', 10, 'Spezial', 'WdZ 105ff.', 'Ritualkenntnis (Tradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Talenttyp, Quelle, WikiLink) VALUES ('Ritualkenntnis (Derwische)', 10, 'Spezial', 'WdZ 105ff.', 'Ritualkenntnis (Tradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Talenttyp, Quelle, WikiLink) VALUES ('Ritualkenntnis (Durro-Dûn)', 10, 'Spezial', 'WdZ 105ff.', 'Ritualkenntnis (Tradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Talenttyp, Quelle, WikiLink) VALUES ('Ritualkenntnis (Zaubertänze)', 10, 'Spezial', 'WdZ 105ff.', 'Ritualkenntnis (Tradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Talenttyp, Quelle, WikiLink) VALUES ('Ritualkenntnis (Zibilja)', 10, 'Spezial', 'WdZ 105ff.', 'Ritualkenntnis (Tradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Talenttyp, Quelle, WikiLink) VALUES ('Ritualkenntnis (Runenzauberei)', 10, 'Spezial', 'WdZ 105ff.', 'Runenkunde');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Geister bannen', 10, 'MU', 'CH', 'KK', 'Spezial', 'WdZ 149', 'Ritualkenntnis (Schamanentradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Geister rufen', 10, 'MU', 'IN', 'CH', 'Spezial', 'WdZ 149', 'Ritualkenntnis (Schamanentradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Geister binden', 10, 'KL', 'IN', 'CH', 'Spezial', 'WdZ 149', 'Ritualkenntnis (Schamanentradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Geister aufnehmen', 10, 'MU', 'IN', 'KO', 'Spezial', 'WdZ 149', 'Ritualkenntnis (Schamanentradition)');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Angrosch)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Aves)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Boron)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Efferd)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Firun)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Hesinde)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Ifirn)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Ingerimm)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Kor)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Namenloser)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Nandus)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Peraine)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Phex)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Praios)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Rahja)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Rondra)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Swafnir)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Travia)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Tsa)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (H''Szint)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');
INSERT INTO Talent (Talentname, TalentgruppeID, Eigenschaft1, Eigenschaft2, Eigenschaft3, Talenttyp, Quelle, WikiLink) VALUES ('Liturgiekenntnis (Zsahh)', 11, 'MU', 'IN', 'CH', 'Spezial', 'WdG 238', 'Liturgiekenntnis');