-- Daten Update Gegner Gareth-Box
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000962' ,N'Veteranen-Mitglied der Alten Gilde' ,NULL ,NULL ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 28' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000963' ,N'Spießbürger (erfahren)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/buerger.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 25' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000964' ,N'Geweihter des Namenlosen (Grad III)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/magier.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 32' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000965' ,N'Veteranen-Waisenmacher-Söldner' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/barbar.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,6 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 31' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000966' ,N'Erfahrenes Mitglied der Tobrier' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/soeldner.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 30' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000967' ,N'Inspector der Garether Criminal-Kammer (erfahren)' ,NULL ,NULL ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 26' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000968' ,N'Bürger oder Einwohner (Gareth)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/buerger.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 24' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000969' ,N'Mitglied der Tobrier' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/soeldner.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 29' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000970' ,N'Stadtgardisten (Kettenhemnd)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/gardist.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,11 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 25' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000971' ,N'Geweihter des Namenlosen (Grad IV)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/magier.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 32' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000972' ,N'Mitglied der Alten Gilde' ,NULL ,NULL ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 27' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000973' ,N'Mitglied der Almadaner (Recambios)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/wegelagerer.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 28' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000974' ,N'Geweihter des Namenlosen (Grad I)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/magier.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 31' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000975' ,N'Stadtgardisten (Gambeson)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/gardist.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,7 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 25' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000976' ,N'Stadtgardist (Veteran, Gambeson)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/gardist.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,7 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 26' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000977' ,N'Stadtgardist (erfahren, Kettenhemnd)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/gardist.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,5 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 25' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000978' ,N'Waisenmacher-Söldner' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/barbar.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,6 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 30' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000979' ,N'Erfahrener Waisenmacher-Söldner' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/barbar.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,6 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 31' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000980' ,N'Inspector der Garether Criminal-Kammer (Veteran)' ,NULL ,NULL ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 27' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000981' ,N'Erfahrenes Mitglied der Alten Gilde' ,NULL ,NULL ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 27, 28' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000982' ,N'Stadtgardist (Veteran, Kettenhemd)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/gardist.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,7 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 26' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000983' ,N'Stadtgardist (erfahren, Gambeson)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/gardist.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,7 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 25' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000984' ,N'Veteranen-Spießbürger' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/buerger.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 25' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000985' ,N'Erfahrenes Mitglied der Almadaner (Bracero)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/wegelagerer.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 28, 29' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000986' ,N'Veteranen-Mitglied der Tobrier' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/soeldner.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 30' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000987' ,N'Veteranen-Mitglied der Almadaner (Caballero)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/wegelagerer.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 29' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000988' ,N'Geweihter des Namenlosen (Grad II)' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/magier.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 31, 32' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000989' ,N'Inspector der Garether Criminal-Kammer' ,NULL ,NULL ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,8 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 26' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
INSERT INTO [GegnerBase] (  [GegnerBaseGUID],  [Name],  [Typ],  [Bild],  [INIBasis],  [INIZufall],  [Aktionen],  [PA],  [LE],  [AU],  [AE],  [KE],  [KO],  [MRGeist],  [MRKörper],  [GS],  [GS2],  [GS3],  [RSKopf],  [RSBrust],  [RSRücken],  [RSArmL],  [RSArmR],  [RSBauch],  [RSBeinL],  [RSBeinR],  [GW],  [Jagd],  [Beschwörung],  [Kontrolle],  [Beschwörungskosten],  [Tags],  [Bemerkung],  [Literatur],  [Setting],  [Verbreitung],  [Jagdreaktion],  [Beute],  [Auftreten],  [AT],  [FK]) 
 VALUES ('00000000-0000-0000-006e-000000000990' ,N'Spießbürger' ,NULL ,N'/DSA MeisterGeister;component/Images/Wesen/buerger.png' ,0 ,N'1W6' ,2 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,7 ,NULL ,NULL ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,NULL ,NULL ,NULL ,NULL ,NULL ,N'Kultur, Säuger, Primat, Homo, Mensch, Mittelländer, Güldenländer' ,NULL ,N'GKuK 24' ,N'Aventurien' ,NULL ,NULL ,NULL ,NULL ,0 ,0);
