-- Regeln
CREATE TABLE Regeln (Name nvarchar(100) PRIMARY KEY, Anwenden bit DEFAULT 1, Typ nvarchar(10) DEFAULT 'Optional', Beschreibung nvarchar(255));
INSERT INTO Regeln (Name, Typ, Beschreibung) VALUES ('EigenschaftenProbePatzerGlück', 'Optional', 'Eigenschafts-Proben: Patzer und Glückswürfe (WdS 7)');

-- Sonderfertigkeiten
ALTER TABLE Sonderfertigkeit ADD HatWert bit DEFAULT 0, Typ nvarchar(20) DEFAULT 'Kampf';
ALTER TABLE Held_Sonderfertigkeit ADD Wert nvarchar(150);
UPDATE Sonderfertigkeit SET HatWert = 0;
UPDATE Sonderfertigkeit SET Typ = 'Allgemein' WHERE SonderfertigkeitID >= 1 AND SonderfertigkeitID <= 11;
UPDATE Sonderfertigkeit SET Typ = 'Kampf' WHERE SonderfertigkeitID >= 12 AND SonderfertigkeitID <= 80;
UPDATE Sonderfertigkeit SET HatWert = 1 WHERE SonderfertigkeitID = 2 OR SonderfertigkeitID = 8 OR SonderfertigkeitID = 11 OR SonderfertigkeitID = 52 OR SonderfertigkeitID = 70 OR SonderfertigkeitID = 78;
DELETE FROM Sonderfertigkeit WHERE SonderfertigkeitID=1;
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Akklimatisierung (Hitze)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Akklimatisierung (Kälte)', 0, 'Allgemein');
DELETE FROM Sonderfertigkeit WHERE SonderfertigkeitID=4;
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Geländekunde (Dschungelkundig)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Geländekunde (Eiskundig)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Geländekunde (Gebirgskundig)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Geländekunde (Höhlenkundig)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Geländekunde (Maraskankundig)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Geländekunde (Meereskundig)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Geländekunde (Steppenkundig)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Geländekunde (Sumpfkundig)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Geländekunde (Waldkundig)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Geländekunde (Wüstenkundig)', 0, 'Allgemein');
DELETE FROM Sonderfertigkeit WHERE SonderfertigkeitID=5;
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Mittelreich)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Almada)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Andergast und Nostria)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Bornland)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Svellttal)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Nordlande)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Horasreich)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Zyklopeninseln)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Amazonen)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Aranien)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Tulamidenlande)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Novadi)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Ferkina)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Zahori)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Thorwal)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Gjalskerländer)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Fjarninger)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Waldmenschen)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Tocamuyac)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Maraskan)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Südaventurien)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Bukanier)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Nivesen)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Norbarden)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Trollzacker)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Schwarze Lande)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Ambosszwerge)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Brillantzwerge)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Erzzwerge)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Hügelzwerge)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Brobim)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Auelfen)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Waldelfen)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Firnelfen)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Steppenelfen)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Orks)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Goblins)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Archaische Achaz)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Stammes-Achaz)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Trolle)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Grolme)', 0, 'Allgemein');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Kulturkunde (Andere)', 1, 'Allgemein');
DELETE FROM Sonderfertigkeit WHERE SonderfertigkeitID=55;
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Scharfschütze (Armbrust)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Scharfschütze (Belagerungswaffen)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Scharfschütze (Blasrohr)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Scharfschütze (Bogen)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Scharfschütze (Diskus)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Scharfschütze (Schleuder)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Scharfschütze (Wurfbeile)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Scharfschütze (Wurfmesser)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Scharfschütze (Wurfspeere)', 0, 'Kampf');
DELETE FROM Sonderfertigkeit WHERE SonderfertigkeitID=47;
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Meisterschütze (Armbrust)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Meisterschütze (Belagerungswaffen)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Meisterschütze (Blasrohr)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Meisterschütze (Bogen)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Meisterschütze (Diskus)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Meisterschütze (Schleuder)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Meisterschütze (Wurfbeile)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Meisterschütze (Wurfmesser)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Meisterschütze (Wurfspeere)', 0, 'Kampf');
DELETE FROM Sonderfertigkeit WHERE SonderfertigkeitID=71;
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Auspendeln)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Beinarbeit)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Biss)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Block)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Doppelschlag)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Eisenarm)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Fußfeger)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Gerade)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Griff)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Halten)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Handkante)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Hoher Tritt)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Klammer)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Knaufschlag)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Knie)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Kopfstoß)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Kreuzblock)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Niederringen)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Schmetterschlag)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Schmutzige Tricks)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Schwanzfeger)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Schwanzschlag)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Schwinger)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Schwitzkasten)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Sprung)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Sprungtritt)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Tritt)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Versteckte Klinge)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Würgegriff)', 0, 'Kampf');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Waffenloses Manöver (Wurf)', 0, 'Kampf');

-- Vor-/Nachteile
ALTER TABLE VorNachteil ADD HatWert bit DEFAULT 0;
ALTER TABLE VorNachteil ADD WertTyp nvarchar(50);
ALTER TABLE Held_VorNachteil ADD Wert nvarchar(255);
UPDATE VorNachteil SET HatWert = 0;
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Adlig (Adlige Abstammung)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Adlig (Adliges Erbe)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Adlig (Amtsadel)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Affinität zu Geistern', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Affinität zu Elementaren', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Affinität zu Dämonen', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Akademische Ausbildung (Gelehrter)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Akademische Ausbildung (Krieger)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Akademische Ausbildung (Magier)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Altersresistenz', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Astrale Regeneration I', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Astrale Regeneration II', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Astrale Regeneration III', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Astralmacht', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Ausdauernd', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Ausdauernder Zauberer', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Ausrüstungsvorteil', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Balance', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Antimagie)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Beschwörung)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Dämonisch (gesamt))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Dämonisch (Blakharaz))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Dämonisch (Belhalhar))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Dämonisch (Charyptoroth))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Dämonisch (Lolgramoth))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Dämonisch (Thargunitoth))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Dämonisch (Amazeroth))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Dämonisch (Belshirash))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Dämonisch (Asfaloth))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Dämonisch (Tasfarelel))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Dämonisch (Belzhorash))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Dämonisch (Agrimoth))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Dämonisch (Belkelel))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Eigenschaften)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Einfluss)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Elementar (gesamt))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Elementar (Humus))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Elementar (Erz))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Elementar (Eis))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Elementar (Feuer))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Elementar (Luft))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Elementar (Wasser))', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Form)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Geisterwesen)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Heilung)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Hellsicht)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Herbeirufung )', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Herrschaft)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Illusion)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Kraft)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Limbus)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Metamagie)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Objekt)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Schaden)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Telekinese)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Temporal)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Umwelt)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Merkmal (Verständigung)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Ritual', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Talent', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Talentgruppe (Kampf)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Talentgruppe (Körper)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Talentgruppe (Gesellschaft)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Talentgruppe (Natur)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Talentgruppe (Wissen)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Talentgruppe (Handwerk)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Talentgruppe (Sprachen und Schriften)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Talentgruppe (Nahkampf)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Talentgruppe (Fernkampf)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Begabung für Zauber', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Beidhändig', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Beseelte Knochenkeule', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Besonderer Besitz', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Breitgefächerte Bildung', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Dämmerungssicht', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Eidetisches Gedächtnis', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Eigeboren', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Eisenaffine Aura', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Empathie', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Entfernungssinn', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Ererbte Knochenkeule', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Feenfreund', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Feste Matrix', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Flink', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Gebildet', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Gefahreninstinkt', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Geräuschhexerei', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Geweiht', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Glück', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Glück im Spiel', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Gut Aussehend', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Guter Ruf', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Gutes Gedächtnis', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Halbzauberer', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Herausragende Balance', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Herausragende Eigenschaft (MU)', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Herausragende Eigenschaft (IN)', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Herausragende Eigenschaft (CH)', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Herausragende Eigenschaft (FF)', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Herausragende Eigenschaft (KL)', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Herausragende Eigenschaft (GE)', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Herausragende Eigenschaft (KK)', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Herausragende Eigenschaft (KO)', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Herausragender Sechster Sinn', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Herausragender Sinn (Gehör)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Herausragender Sinn (Sicht)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Herausragender Sinn (Tastsinn)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Herausragender Sinn (Geruchssinn)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Herausragendes Aussehen', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Hitzeresistenz', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Hohe Lebenskraft', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Hohe Magieresistenz', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Immunität gegen Gift', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Immunität gegen Krankheiten', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Innerer Kompass', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Kälteresistenz', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Kampfrausch', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Koboldfreund', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Kräfteschub', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Talentschub', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Linkshänder', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Machtvoller Vertrauter', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Magiedilettant', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Magiegespür', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Meisterhandwerk', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Nachtsicht', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Natürliche Waffen', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert, WertTyp) VALUES ('Natürlicher Rüstungsschutz', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Niedrige Schlechte Eigenschaft', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Prophezeien', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Resistenz gegen Gift', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Resistenz gegen Krankheiten', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Richtungssinn', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Schlangenmensch', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Schnelle Heilung I', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Schnelle Heilung II', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Schnelle Heilung III', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Schutzgeist', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Schwer zu verzaubern', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Soziale Anpassungsfähigkeit', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Tierempathie', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Tierfreund', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Übernatürliche Begabung', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Unbeschwertes Zaubern', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Verbindungen', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Verhüllte Aura', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Veteran', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Viertelzauberer', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Vollzauberer', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Vom Schicksal begünstigt', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Wesen der Nacht', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Wohlklang', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Wolfskind (wissentlich)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Wolfskind (intuitiv)', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Zäher Hund', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Zauberhaar', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Zeitgefühl', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Zusätzliche Gliedmaßen', 1, 1);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Zweistimmiger Gesang', 1, 0);
INSERT INTO VorNachteil (Name, Vorteil, HatWert) VALUES ('Zwergennase', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Aberglaube', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Albino', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Angst vor', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Animalische Magie', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Arkanophobie', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Arroganz', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Artefaktgebunden', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Astraler Block', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Autoritätsgläubig', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Behäbig', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Blutdurst', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Blutrausch', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Brünstigkeit', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Dunkelangst', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Einarmig', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Einarmig (gelähmt/verkrüppelt)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Einäugig', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Einbeinig', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Einbildungen', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Eingeschränkte Elementarnähe', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Eingeschränkter Sinn (schwerhörig)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Eingeschränkter Sinn (kurzsichtig)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Eingeschränkter Sinn (Tastsinn)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Eingeschränkter Sinn (Geruchssinn)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Einhändig', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Eitelkeit', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Elfische Weltsicht', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Farbenblind', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Feind', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Feste Gewohnheit', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Festgefügtes Denken', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Fettleibig', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Fluch der Finsternis', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Geiz', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Gerechtigkeitswahn', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Gesucht I', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Gesucht II', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Gesucht III', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Goldgier', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Größenwahn', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Heimwehkrank', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Hitzeempfindlichkeit', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Höhenangst', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Impulsiv', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Jähzorn', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Kälteempfindlichkeit', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Kältestarre', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Kein Vertrauter', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Kleinwüchsig', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Körpergebundene Kraft', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Krankhafte Reinlichkeit', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Krankheitsanfällig', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Kristallgebunden', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Kurzatmig', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Lahm', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Lästige Mindergeister', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Lichtempfindlich', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Lichtscheu', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Madas Fluch', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Medium', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Meeresangst', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Miserable Eigenschaft', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Mondsüchtig', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Moralkodex Kirche', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Nachtblind', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Nahrungsrestriktion', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Neid', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Neugier', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Niedrige Astralkraft', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Niedrige Lebenskraft', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Niedrige Magieresistenz', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Pechmagnet', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Platzangst', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Prinzipientreue', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Rachsucht', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Randgruppe', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Raubtiergeruch', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Raumangst', 1, 1,'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Rückschlag', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Schlafstörungen I', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Schlafstörungen II', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Schlafwandler', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Schlechte Regeneration', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Schlechter Ruf', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Schneller Alternd', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Schulden', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Schwache Ausstrahlung', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Schwacher Astralkörper', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Schwanzlos', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Seffer Manich', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Selbstgespräche', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Sensibler Geruchssinn', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Sippenlosigkeit', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Sonnensucht', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Speisegebote', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Spielsucht', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Sprachfehler', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Spruchhemmung', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Stigma', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Streitsucht', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Stubenhocker', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Sucht', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Thesisgebunden', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Tollpatsch', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Totenangst', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Übler Geruch', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unangenehme Stimme', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unansehnlich', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Antimagie)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Beschwörung)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Dämonisch)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Eigenschaften)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Einfluss)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Elementar)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Form)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Geisterwesen)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Heilung)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Hellsicht)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Herbeirufung )', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Herrschaft)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Illusion)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Kraft)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Limbus)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Metamagie)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Objekt)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Schaden)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Telekinese)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Temporal)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Umwelt)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Merkmal (Verständigung)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Talent', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Talentgruppe (Gesellschaft)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Talentgruppe (Wissen)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Talentgruppe (Handwerk)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Talentgruppe (Natur)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Talentgruppe (Sprachen und Schriften)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Talentgruppe (Kampf)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Talentgruppe (Körper)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Talentgruppe (Nahkampf)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfähigkeit für Talentgruppe (Fernkampf)', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unfrei', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Ungebildet', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unstet', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Unverträglichkeit mit verarbeitetem Metall', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Vergesslichkeit', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Verpflichtungen', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Verschwenungssucht', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Verwöhnt', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Vorurteile', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Wahnvorstellungen', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Wahrer Name', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Weltfremd', 1, 1);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Widerwärtiges Aussehen', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Wilde Magie', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Zielschwierigkeiten', 1, 0);
INSERT INTO VorNachteil (Name, Nachteil, HatWert, WertTyp) VALUES ('Zögerlicher Zauberer', 1, 1, 'int');
INSERT INTO VorNachteil (Name, Nachteil, HatWert) VALUES ('Zwergenwuchs', 1, 0);

-- Talente
ALTER TABLE Talent ADD WikiLink nvarchar(200);
UPDATE Talent SET WikiLink ='Anderthalbhänder (Talent)' WHERE Talentname ='Anderthalbhänder';
UPDATE Talent SET WikiLink ='Blasrohr (Talent)' WHERE Talentname ='Blasrohr';
UPDATE Talent SET WikiLink ='Diskus (Talent)' WHERE Talentname ='Diskus';
UPDATE Talent SET WikiLink ='Peitsche (Talent)' WHERE Talentname ='Peitsche';
UPDATE Talent SET WikiLink ='Säbel (Talent)' WHERE Talentname ='Säbel';
UPDATE Talent SET WikiLink ='Schleuder (Talent)' WHERE Talentname ='Schleuder';
UPDATE Talent SET WikiLink ='Wurfmesser (Talent)' WHERE Talentname ='Wurfmesser';
UPDATE Talent SET Quelle='WdS 189-190' WHERE TalentgruppeID=8;
UPDATE Talent SET Quelle='WdS 30-32' WHERE TalentgruppeID=7;
UPDATE Talent SET Quelle='WdH 250' WHERE Talentname='Empathie';
UPDATE Talent SET Quelle='WdH 251' WHERE Talentname='Gefahreninstinkt';
UPDATE Talent SET Quelle='WdH 251' WHERE Talentname='Geräuschhexerei';
UPDATE Talent SET Quelle='WdH 254-255' WHERE Talentname='Magiegespür';
UPDATE Talent SET Quelle='WdH 255' WHERE Talentname='Prophezeien';
UPDATE Talent SET Quelle='WdH 259' WHERE Talentname='Zwergennase';
UPDATE Talent SET WikiLink ='Altes Kemi (Schrift)' WHERE Talentname ='Lesen/Schreiben (Altes Kemi)';
UPDATE Talent SET WikiLink ='Angram (Schrift)' WHERE Talentname ='Lesen/Schreiben (Angram)';
UPDATE Talent SET WikiLink ='Chrmk' WHERE Talentname ='Lesen/Schreiben (Chrmk/Zelemja)';
UPDATE Talent SET WikiLink ='Chuchas' WHERE Talentname ='Lesen/Schreiben (Chuchas/Yash-Hualay-Glyphen)';
UPDATE Talent SET WikiLink ='Isdira (Schrift)' WHERE Talentname ='Lesen/Schreiben (Isdira/Asdharia)';
UPDATE Talent SET WikiLink ='Rogolan (Schrift)' WHERE Talentname ='Lesen/Schreiben (Rogolan)';
UPDATE Talent SET Talentname ='Lesen/Schreiben (Trollische Raumbilderschrift)' WHERE Talentname ='Lesen/Schreiben (Trolloische Raumbilder)';
UPDATE Talent SET WikiLink ='Tulamidya (Schrift)' WHERE Talentname ='Lesen/Schreiben (Tulamidya)';
UPDATE Talent SET WikiLink ='Ur-Tulamidya (Schrift)' WHERE Talentname ='Lesen/Schreiben (Ur-Tulamidya)';
UPDATE Talent SET WikiLink ='Zhayad (Schrift)' WHERE Talentname ='Lesen/Schreiben (Zhayad)';
UPDATE Talent SET WikiLink ='Tulamidya (Sprache)' WHERE Talentname ='Sprachen Kennen (Tulamidya)';
UPDATE Talent SET WikiLink ='Ur-Tulamidya (Sprache)' WHERE Talentname ='Sprachen Kennen (Ur-Tulamidya)';
UPDATE Talent SET WikiLink ='Ferkina (Sprache)' WHERE Talentname ='Sprachen Kennen (Ferkina)';
UPDATE Talent SET WikiLink ='Altes Kemi (Sprache)' WHERE Talentname ='Sprachen Kennen (Altes Kemi)';
UPDATE Talent SET WikiLink ='Rogolan (Sprache)' WHERE Talentname ='Sprachen Kennen (Rogolan)';
UPDATE Talent SET WikiLink ='Angram (Sprache)' WHERE Talentname ='Sprachen Kennen (Angram)';
UPDATE Talent SET Quelle='WdS 34', Voraussetzungen='10+: Gesteinskunde 4', Spezialisierungen='Bergwerke, Kanalisiation, natürliche Höhlen, Sappeur, unterirdische Städte' WHERE Talentname='Bergbau';
UPDATE Talent SET Quelle='WdS 34', Voraussetzungen='Holzbearbeitung 4', Spezialisierungen='Armbrust, Bogen, Bolzen/Pfeile, Torsionswaffen' WHERE Talentname='Bogenbau';
UPDATE Talent SET Quelle='WdS 34', Spezialisierungen='Einmaster (Segeln), Flöße (Staken), Kanus/Kajaks (Paddeln), Ruderboote (Rudern), Eissegler' WHERE Talentname='Boote Fahren';
UPDATE Talent SET Quelle='WdS 34', WikiLink ='Brauer (Talent)' WHERE Talentname='Brauer';
UPDATE Talent SET Quelle='WdS 34', Voraussetzungen='Lesen/Schreiben 6, Mechanik 4, Malen/Zeichnen 4', Spezialisierungen='Buchdruck, Druckereitechnik, Pamphlete, Typographie', WikiLink ='Drucker (Talent)' WHERE Talentname ='Drucker';
UPDATE Talent SET Quelle='WdS 34', Spezialisierungen='Lastkarren, Streitwagen, Zuggespanne, Hunde- und Dachsschlitten' WHERE Talentname='Fahrzeug Lenken';
UPDATE Talent SET Quelle='WdS 34', Voraussetzungen='Menschenkenntnis 4', Spezialisierungen='Würfel, Karten' WHERE Talentname='Falschspiel';
UPDATE Talent SET Quelle='WdS 35', Voraussetzungen='Malen/Zeichnen 4', Spezialisierungen='Gold- und Silberschmied, Gravieren, Schlösser, Siegelstöcke, Trickwaffen/Fallen, Uhrwerke' WHERE Talentname='Feinmechanik';
UPDATE Talent SET Quelle='WdS 35' WHERE Talentname='Feuersteinbearbeitung';
UPDATE Talent SET Quelle='WdS 35', Spezialisierungen='Fische, Geflügel, Reptilien, Säugetiere', WikiLink ='Fleischer (Talent)' WHERE Talentname ='Fleischer';
UPDATE Talent SET Quelle='WdS 35', Spezialisierungen='Gerber, Kürschner, Trophäen' WHERE Talentname='Gerber/Kürschner';
UPDATE Talent SET Quelle='WdS 35', Spezialisierungen='Fensterscheiben, Glasbläserei, Linsenschleifen, Spiegel' WHERE Talentname='Glaskunst';
UPDATE Talent SET Quelle='WdS 35', Spezialisierungen='Drahtzieher/Sarwirker, Hufschmied, Plättner, Schwarzschmied, Spengler, Waffenschmied', WikiLink ='Grobschmied (Talent)' WHERE Talentname ='Grobschmied';
UPDATE Talent SET Quelle='WdS 35', Voraussetzungen='Rechnen 4', Spezialisierungen='nach Region (Thorwal, Weiden, Mhanadistan ...) oder nach Warengruppe (Korn, Metalle, Sklaven, Geldwechsel ...)' WHERE Talentname='Handel';
UPDATE Talent SET Quelle='WdS 36', Spezialisierungen='Bewirtung/Feiern, Personal, Vorratshaltung' WHERE Talentname='Hauswirtschaft';
UPDATE Talent SET Quelle='WdS 36', Spezialisierungen='nach Art (alchimistische/Zaubergifte, mineralische Gifte, pflanzliche Gifte, tierische Gifte) oder Wirkung (Atemgifte, Einnahmegifte, Kontaktgifte, Waffengifte), Tierheilkunde' WHERE Talentname='Heilkunde Gift';
UPDATE Talent SET Quelle='WdS 36', Spezialisierungen='nach Region, Tierheilkunde' WHERE Talentname='Heilkunde Krankheiten';
UPDATE Talent SET Quelle='WdS 36' WHERE Talentname='Heilkunde Seele';
UPDATE Talent SET Quelle='WdS 37', Spezialisierungen='Brüche/Quetschungen, Innere Verletzungen, Schnitte, Tierheilkunde, Verbrennungen, Zahnleiden' WHERE Talentname='Heilkunde Wunden';
UPDATE Talent SET Quelle='WdS 38', Spezialisierungen='Beinschnitzerei, Holzkunde,Holzwaffen, Küfer/Wagner, Möbelschreinerei/Tischlerei, Schnitzen' WHERE Talentname='Holzbearbeitung';
UPDATE Talent SET Quelle='WdS 38', Voraussetzungen='Holzbearbeitung 4, Feinmechanik 4,Musizieren 4', Spezialisierungen='Blasintrumente, Saiteninstrumente, Tasteninstrumente, Trommeln', WikiLink ='Instrumentenbauer (Talent)' WHERE Talentname ='Instrumentenbauer';
UPDATE Talent SET Quelle='WdS 38', Voraussetzungen='Malen/Zeichnen 4', Spezialisierungen='Gebäude, Höhlen/Tunnel, Küsten/Meere, Landschaften, Stadt' WHERE Talentname='Kartographie';
UPDATE Talent SET Quelle='WdS 38', Spezialisierungen='Backen/Braten, Festmahle, Haltbarmachen, Marschversorgung, Tränke, Vorkoster' WHERE Talentname='Kochen';
UPDATE Talent SET Quelle='WdS 38' WHERE Talentname='Kristallzucht';
UPDATE Talent SET Quelle='WdS 38', Spezialisierungen='Gurte/Riemen,Lederkleidung, Lederrüstungen, Sättel, Schuhwerk' WHERE Talentname='Lederarbeiten';
UPDATE Talent SET Quelle='WdS 39', Spezialisierungen='Architektur, Landschaften, Porträt, technische Skizze' WHERE Talentname='Malen/Zeichnen';
UPDATE Talent SET Quelle='WdS 39', Spezialisierungen='Steinbau, Steinguss, Ziegelbau', WikiLink ='Maurer (Talent)' WHERE Talentname ='Maurer';
UPDATE Talent SET Quelle='WdS 39', Voraussetzungen='Hüttenkunde 4', Spezialisierungen='Klangkörper, Rohre, Reliefplatten/Statuen' WHERE Talentname='Metallguss';
UPDATE Talent SET Quelle='WdS 39', Spezialisierungen='Blechblasinstrumente, Flöten, Harfen, Kapellmeister/Dirigent, Lauten, Rhythmusinstrumente, Streichinstrumente, Tasteninstrumente' WHERE Talentname='Musizieren';
UPDATE Talent SET Quelle='WdS 39', Spezialisierungen='Fallen, Schlösser' WHERE Talentname='Schlösser Knacken';
UPDATE Talent SET Quelle='WdS 39', Spezialisierungen='alchimistische Destillation, Beeren-/Obstbrände, Kornbrände, Kräuterschnäpse, Lagerung' WHERE Talentname='Schnaps Brennen';
UPDATE Talent SET Quelle='WdS 39', Spezialisierungen='Entwurf/Festgewänder, Flick-/Gebrauchsschneiderei, Maßschneidern, Tuchrüstungen' WHERE Talentname='Schneidern';
UPDATE Talent SET Quelle='WdS 40', Spezialisierungen='Ruderschiff, Segelschiff, Steuermann' WHERE Talentname='Seefahrt';
UPDATE Talent SET Quelle='WdS 40', WikiLink ='Seiler (Talent)' WHERE Talentname ='Seiler';
UPDATE Talent SET Quelle='WdS 40', Voraussetzungen='Gesteinskunde 4', Spezialisierungen='Baugestein, Reliefs, Statuen', WikiLink ='Steinmetz (Talent)' WHERE Talentname ='Steinmetz';
UPDATE Talent SET Quelle='WdS 40', Voraussetzungen='10+: Gesteinskunde 4' WHERE Talentname='Steinschneider/Juwelier';
UPDATE Talent SET Quelle='WdS 40', Voraussetzungen='Holzbearbeitung 4, Lederarbeiten 4, Grobschmied 4', Spezialisierungen='Karren/Wagen, Schlitten, Streitwagen', WikiLink ='Stellmacher (Talent)' WHERE Talentname ='Stellmacher';
UPDATE Talent SET Quelle='WdS 40', Spezialisierungen='alchimistische Farben, mineralische Farben, pflanzliche Farben, tierische Farben oder nach Art des Stoffes oder Stoffdruck' WHERE Talentname='Stoffe Färben';
UPDATE Talent SET Quelle='WdS 40', Voraussetzungen='Malen/Zeichnen 4', Spezialisierungen='Naturalistische Darstellungen, Ornamente, Zaubertätowierungen' WHERE Talentname='Tätowieren';
UPDATE Talent SET Quelle='WdS 40', Spezialisierungen='Gefäße, Statuetten, Ziegelei' WHERE Talentname='Töpfern';
UPDATE Talent SET Quelle='WdS 40', Spezialisierungen='nach Tierart: Rind, Schaf/Ziege, Schwein, Pferd, Hund, etc.' WHERE Talentname='Viehzucht';
UPDATE Talent SET Quelle='WdS 41', Spezialisierungen='nach Material oder nach Technik (Häkeln, Klöppeln, Stricken, Teppichknüpfen, Weben)' WHERE Talentname='Webkunst';
UPDATE Talent SET Quelle='WdS 41', Spezialisierungen='Wein, Fruchtweine, Schaumweine, Weinkenner', WikiLink ='Winzer (Talent)' WHERE Talentname ='Winzer';
UPDATE Talent SET Quelle='WdS 41', Voraussetzungen='10+: Holzbearbeitung 4', Spezialisierungen='Dachdecker, Holzkonstruktionen, Schiffszimmermann, Schiffbau (erfordert die Talente Lesen/Schreiben, Malen/Zeichnen, Rechnen und Seefahrt jeweils auf TaW 4)', WikiLink ='Zimmermann (Talent)' WHERE Talentname ='Zimmermann';