-- Not Null und Default bei der Tabelle Waffe
ALTER TABLE [Waffe] ALTER COLUMN [TPWürfel] int NOT NULL
GO
ALTER TABLE [Waffe] ALTER COLUMN [TPWürfel] SET DEFAULT 6
GO
ALTER TABLE [Waffe] ALTER COLUMN [TPWürfelAnzahl] int NOT NULL
GO
ALTER TABLE [Waffe] ALTER COLUMN [TPWürfelAnzahl] SET DEFAULT 0
GO
ALTER TABLE [Waffe] ALTER COLUMN [TPBonus] int NOT NULL
GO
ALTER TABLE [Waffe] ALTER COLUMN [TPBonus] SET DEFAULT 0
GO
ALTER TABLE [Waffe] ALTER COLUMN [AusdauerSchaden] bit NOT NULL
GO
ALTER TABLE [Waffe] ALTER COLUMN [Gewicht] int NOT NULL
GO
ALTER TABLE [Waffe] ALTER COLUMN [Gewicht] SET DEFAULT 0
GO
ALTER TABLE [Waffe] ALTER COLUMN [Preis] float NOT NULL
GO
ALTER TABLE [Waffe] ALTER COLUMN [Preis] SET DEFAULT 0
GO