-- Schamanenrituale
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Abvenenum reine Speise', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Adlerschwinge Wolfsgestalt', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Arngrimms Höhle', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Attributo', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Aufmerksamer Wächter', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Blick in die Vergangenheit', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Blick in Liskas Auge', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Blick ins Geisterreich', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Blick ins Geisterreich (II)', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Blick ins Geisterreich (III)', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Blutsbund', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Brazoragh Ghorkai - Brazoraghs Hieb ', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Ergochai Tairachi -Tairachs Sklaven', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Exorzismus', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Exorzismus (III)', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Exorzismus (IV)', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Exorzismus (V)', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Farben des Krieges', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Fluch der Pestilenz', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Fluch der Verwirrung', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Freie Seelenfahrt', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Gaben der Erde', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Geisterbote', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Geisterkerker', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Geistheilung', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Geleit des Nipakau', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Gesang der Wölfe', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Gharyak Maruki', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Großer Geisterbann', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Großer Geisterbann (III)', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Großer Geisterbann (IV)', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Großer Geisterbann (V)', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Großer Geisterbann (VI)', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Hairuf', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Halluzination', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Harmlose Gestalt', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Haselbusch und Ginsterkraut', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Hauch des Elements', 1, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Heimführung der Herde', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Herr über das Tierreich', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Herz des Tieres', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Hilferuf', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Invocatio minor', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Jagdfieber', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Khurkachai Tairachi -Tairachs Krieger', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Kraft der Tayas', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Kraft des Tieres', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Macht der Elemente ', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Macht des Blutes', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Magischer Raub', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Mailam Rekdais Segen', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Mammutruf', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Manifesto Element', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: M''char Utrak Rikaii - Rikais Alchimie', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Ogerruf', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Pfad der Blutrache', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Rat der Ahnen', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Regentanz ', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Reinigen des Wassers', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Reißgrams Fährte', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Reitender Geist', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Rikais Verderben', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Rinderruf', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Ruf des Schamanen', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Sanftmut', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Schlangenfluch', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Schlangenfluch (V)', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Schlangengeist', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Schlingerruf', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Schomas Kraft ', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Schutz der Jurte', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Schützende Rotte', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Seelenwanderung', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Seeschlangenruf', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Stimme des Nipakau', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Tabuzone', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Tauschplatz', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Tiere aus Farben', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Tiergedanken', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Tränke meine Herde', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Weckruf', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Weg des Windes', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Wegzeichen', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Weidegründe finden', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Wettermeisterschaft', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Wild finden', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Wildschweinruf', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Wolfsfluch', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Wolfsfluch (V)', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Wolfsruf', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Zauberklinge Geisterspeer', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Zeichen setzen', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Zorn des Berglöwen', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ) VALUES ('Schamanenritual: Zwingtanz', 0, 'Magisch (Schamanenritual)');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ, Setting) VALUES ('Schamanenritual: Visars Sklaven', 0, 'Magisch (Schamanenritual)', 'Dunkle Zeiten');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ, Setting) VALUES ('Schamanenritual: Visars Krieger', 0, 'Magisch (Schamanenritual)', 'Dunkle Zeiten');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ, Setting) VALUES ('Schamanenritual: Hilferuf (III)', 0, 'Magisch (Schamanenritual)', 'Dunkle Zeiten');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ, Setting) VALUES ('Schamanenritual: Anrufung des Yaq-Hai', 0, 'Magisch (Schamanenritual)', 'Dunkle Zeiten');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ, Setting) VALUES ('Schamanenritual: Siedendes Blut', 0, 'Magisch (Schamanenritual)', 'Dunkle Zeiten');
INSERT INTO Sonderfertigkeit (Name, HatWert, Typ, Setting) VALUES ('Schamanenritual: Tschumbi', 0, 'Magisch (Schamanenritual)', 'Dunkle Zeiten');